### PR TITLE
Loader

### PR DESCRIPTION
**Pull request by dmarcos**
It provides a loader for scenes to show something on screen while assets and the scene initializes. It demotes `canvas` and `vr-mode-ui` to libraries from components. The loader needs them before components initialize.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Glad to review this if it’s still on the roadmap. Or perhaps we should create an external component if we’re hesitant to put this in core?

**Comment by dmarcos** [comment]
This needs more work. We will postpone for 0.9.0

**Comment by VasuBhog** [comment]
Hi I wanted to know if this is still in implementation or if there is another component out there that has same functionality to create a "load screen" before all assets are loaded fluidly.

**Comment by dmarcos** [comment]
This functionality has landed on a different PR.

**Pull request closed without merging**
