### PR TITLE
Replace goggles icon with a fullscreen one when webVR is not availabl…

### PR DESCRIPTION
**Pull request by dmarcos**

### CODE REVIEW

**Comment by dmarcos** [comment]
embedded

anime

**Comment by ngokevin** [comment]
We can do this after, but:

- The fullscreen icon can be less pronounced. It looks a bit like a puzzle piece or a pattern.
- Reintroduce the modal that mentions VR.

**Comment by dmarcos** [comment]
@ngokevin I would not reintroduce the modals. Modals are annoying and most people don't read them. The button behaves properly given the environment capabilities so the modals are redundant.

**Comment by dmarcos** [comment]
An application seamlessly behaving in the best possible way given the available capabilities is what graceful degradation is about.

**Comment by ngokevin** [comment]
ok sure

**Pull request merged**
