### PR TITLE
make stats an entity injected into camera so they are visible in and …

### PR DESCRIPTION
**Pull request by machenmusik**
**Description:**
make stats an entity injected into camera so they are visible in and out of VR

**Changes proposed:**
src/components/scene/stats.js

### CODE REVIEW

**Comment by machenmusik** [comment]
to the extent that the current stats component is useful, this should be a nice improvement;
not sure what is going on with the failed check though, advice welcome

**Comment by machenmusik** [comment]
(@ngokevin are there any issues, or has no one had a chance to look at it yet?)

**Comment by machenmusik** [comment]
In the meantime, this is available as `stats-in-vr` component in registry, if we want to include in core, should probably pull in latest changes

**Comment by ngokevin** [comment]
I think this could live as a third-party component for now. Could even be simpler, just reading the rStats value and outputting with text component.

**Comment by machenmusik** [comment]
Agree this can live as a 3rd party component, and that the original PR is stale now... although really something should be done to the built-in stats to make them not entirely useless in VR.

**Pull request closed without merging**
