### PR TITLE
Fixed WebVR hands rotation offset on X axes (fixes #4719)

### LINKED ISSUE #4719: VR hands 45 rotation offset on X axes (WebVR)
**Description:**

Apparently, when using `WebVR` (Firefox `82.0.3`) the VR hands from `hand-controls` have a `45`° rotation offset around the `X` axes, which doesn't provide correct VR embodiment.

vr-hands-45-rotation-offset-webvr

This seems to be caused by a `43` value on the `X` axes set in the `orientationOffset` property of the `oculus-touch-controls` core component.

( see image below at line `70508`)

oculus-touch-controls-root-cause

The issue can be fixed by setting that `X` value in `orientationOffset` to `0`.

- A-Frame Version:
`1.0.4` 

- Platform / Device:
Oculus Rift / Rift S

- Reproducible Code Snippet or URL:
https://vr-hands-45-rotation-offset-webvr.glitch.me/

### PR DESCRIPTION
**Pull request by thedart76**
**Description:**

This PR fixes a **~45°** `rotation` offset of the VR hands (from `hand-controls`) around their `X` axes when using WebVR (Firefox 82.0.3)

**Changes proposed:**

To achieve correct VR embodiment the default `orientationOffset` value in the `schema` of the `oculus-touch-controls` component could be set as follows:

`orientationOffset: {type: 'vec3', default: {x: 0, y: 0, z: 0}}`

Further details and images in issue #4719

### CODE REVIEW

**Comment by dmarcos** [comment]
What's the impact with WebXR and other hedsets / browser like for instance Oculus Quest an Oculus Browser?

**Comment by thedart76** [comment]
Before fixing the conflict, I had this line of code:

`controllerType: {default: 'auto', oneOf: ['auto', 'oculus-touch', 'oculus-touch-v2']},`

All testing done with WebXR on Oculus Quest and Quest browser was successful, meaning that the WebXR hands were not impacted by setting:

`orientationOffset: {type: 'vec3', default: {x: 0, y: 0, z: 0}}`

IDK if accepting the following line of code to resolve the conflict could create any issue:

`controllerType: {default: 'auto', oneOf: ['auto', 'oculus-touch', 'oculus-touch-v2', 'oculus-touch-v3']},`

Do you think this might be the case?

If so, I am happy to test it once more and LYK.

**Comment by dmarcos** [comment]
Thanks! Yeah I think we should add `oculus-touch-v3` and see how it affects Quest 2. I have one if you can't test on one.

**Comment by thedart76** [comment]
Sounds good. Yes, I can test on Quest 2 as well. I will get back to you over the next days.

**Comment by thedart76** [comment]
Hey @dmarcos , I was going to test on Quest 2, but when I use the A-Frame `master` build (which includes `oculus-touch-v3`) I get the below errors in Console:

testing-aframe-master

Can you shed light on this?

**Comment by dmarcos** [comment]
A bug. You can rebase on master. Sorry for the inconvenience

**Comment by dmarcos** [comment]
WebVR has been deprecated so this no longer applies. Thanks

**Pull request closed without merging**
