### PR TITLE
Set 72Hz mode by default on Oculus Browser (fix #4232)

### LINKED ISSUE #4232: Oculus Browser: new release is locked to 60fps
**Description:**

- A-Frame Version: 0.92
- Platform / Device: Oculus Quest with new update (333770.2680.0)
- Reproducible Code Snippet or URL:

When you enter an AFrame demo with the new update, the FPS is locked to 60fps. This gives a noticeable (to some people) flicker to the whole scene.

You can fix this using highRefreshRate. But it used to be automatic

### PR DESCRIPTION
**Pull request by dmarcos**

### CODE REVIEW

**Comment by kennardconsulting** [comment]
No, https://rawgit.com/aframevr/aframe/master/dist/aframe-master.js does not work as time of writing.

It is 60Hz. Adding highRefreshRate fixes it and is immediately noticeable

**Comment by dmarcos** [comment]
rawgit doesn’t contain the changes sincs the PR hasn’t been merged yet. You have to fetch and test locally.

**Comment by kennardconsulting** [comment]
Last commit to https://github.com/aframevr/aframe/commits/master was 4 days ago. Do I assume this fix isn't there yet?

**Comment by dmarcos** [comment]
No. the necessary changes are in this PR that I’m looking for feedback before merge.

**Comment by kennardconsulting** [comment]
I understand. Okay, where are instructions to build the /dist from src? Sorry I'm not seeing the build environment I'm used to.

**Comment by dmarcos** [comment]
Fetch the branch `npm install`  `npm start` and visit `http://localhost:9000/examples/` to see the examples. From Quest look for your computer local IP: `http://xxx.xxx.xxx.xxx:9000/examples/`

**Comment by jhb** [comment]
Just finished the following (maybe this helps @kennardconsulting ):

```
  git clone https://github.com/dmarcos/aframe.git
  cd aframe
  npm install
  git checkout master
  npm start
  <open http://<my laptop>:9000/ and there "hello world", lots of flicker>
  <ctrl-c>
  git checkout 72fps
  <open http://<my laptop>:9000/ and there "hello world", no flicker>
  <happy dance>
```
So yes, i would say it works!. Sidenote: the flicker is better to see if there is a light/white background.

Thanks a lot, @dmarcos

**Comment by dmarcos** [comment]
@jhb Thanks for the feedback. Much appreciated 🙇

**Comment by kennardconsulting** [comment]
Okay thanks for the detailed instructions @jhb. Yes, confirmed: it's bad in master, but fixed in 72fps branch.

Thanks @dmarcos

**Pull request merged**
