### PR TITLE
change default animation easing method as linear #1333

### PR DESCRIPTION
**Pull request by gasolin**
**Changes proposed:**
- set default animation type as 'linear' https://github.com/aframevr/aframe/blob/master/src/constants/animation.js#L15
- update doc accordingly

### CODE REVIEW

**Comment by ngokevin** [comment]
Defaults live at https://github.com/aframevr/aframe/pull/1421/files#diff-cc37208f3a65c67afe166320bf095ca6R10

**Comment by ngokevin** [comment]
@dmarcos Approve the idea? I've built a bunch of scenes, I almost always want `linear` over `ease`.

**Comment by dmarcos** [comment]
The conventional wisdom is that animations should always have some easing because it's how natural movement occurs in real world. Linear animations usually feel unnatural. Look at how biological systems move and operate and how that influence animations in UIs and games. @ngokevin why did you prefer linear over ease in your experiments?

**Comment by ngokevin** [comment]
I've used animations for:

- Falling. A cheap way for gravity.
- Continuous movement. Like a butterfly flying around a try, or something running, or like a plane/car. Or a laser. Something on a conveyor belt.

But those are probably exceptions, and even then they would probably have some miniscule easing. so I agree. Linear is unnatural. Sorry for the goose chase, @gasolin

**Pull request closed without merging**
