### PR TITLE
resolved 404page errors & updated redirection link

### PR DESCRIPTION
**Pull request by akshit13**
**Description:**

**Changes proposed:**
- links were generating 404 page error, after correction the problem resolved.
- proper reference was not given for "entity-component-system",hence added.

### CODE REVIEW

**Comment by ngokevin** [comment]
This is an issue with `aframevr/aframe-site` repo, I will check it out. Thanks!

**Comment by akshit13** [comment]
Should I create a pull request there?

**Comment by ngokevin** [comment]
It's a backend/Node issue.

**Comment by akshit13** [comment]
ok.

**Comment by ngokevin** [comment]
Fixed! Had a minify step that was overriding some of our link processing steps.

**Pull request closed without merging**
