### PR TITLE
clean up memory on scene detachment

### PR DESCRIPTION
**Pull request by kkota1**
clean up memory on scene detachment
add back (mistakenly removed?) setupRenderer call

**Description:**
Fixes the following issues:
- If you have an SPA that can detach scenes, the browser tab will continue to hold onto that memory until the page is refreshed or navigation occurs via location.href. This is due to a buildup of unused webgl contexts.
- Additionally, not all geometries and materials are disposed on scene detachment. I haven't measured whether these ultimately get cleared by GC, but I think it wouldn't hurt to manually dispose them.
- There was a breaking change that removed the setupRenderer call.

**Changes proposed:**
- force webglrenderer context loss on scene detach
- traverse object3D and dispose mats and geos on scene detach
- add back setupRenderer call

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks. `setupRenderer` issue has been fixed on master. You can rebase. Can we move the deallocation logic to a separate function at the bottom? Like [setupCanvas](https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L893) for instance. We can do:

```
  function disposeTHREEResources(object3D) {
      if (!object3D) { return; }
      disposeObject3DResources (object3D);

      if (object3D.children && object3D.children.length) {
         object3D.children.forEach(function (child) {
            disposeTHREEResources(child);
         });
      }

       function disposeObject3DResources (object3D) {
          if (object3D.geometry) { object3D.geometry.dispose();  }
          if (object3D.material) {
            if (object3D.material.length) {
              object3D.material.forEach(function (material) { material.dispose(); });
            } else {
              object3D.material.dispose();
            }
          }
      }
  }
```

**Comment by arpu** [comment]
maybe interesting for this https://github.com/mrdoob/three.js/pull/20478

**Comment by kkota1** [comment]
@dmarcos Rebased and moved the function out but I couldn't figure out how to fix some tests
@arpu object3Ds are already removed via a-entity detachedCallback. Disposal is a separate issue

**Comment by dmarcos** [comment]
Thanks! I think something went wrong when rebasing. Also don't commit content in the `dist` directory.

**Comment by kkota1** [comment]
I believe the dist change is the merge commit from the rebase. I didn’t
make any changes there

**Comment by dmarcos** [comment]
If the rebase went as expected the PR should only have your changes on top of master

**Comment by kkota1** [comment]
Yeah no issues. This is the changeset that will be applied if merged: https://github.com/aframevr/aframe/compare/master...kkota1:master

For me, git always shows merge commit changes in PRs even though they have already been applied to master. So it looks like I changed dist but I didn't

**Comment by dmarcos** [comment]
Look at the PR commit history. There are commits of mine that should not be there. You can do `git rebase -i origin/master` and can remove those.

**Comment by kkota1** [comment]
I think it shows that because the rebase had a merge conflict. It's confusing but I've seen this issue for 6+ years that I've been working on team git projects. I can try to fix later

**Comment by kkota1** [comment]
attempting reopen

**Comment by kkota1** [comment]
fyi https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

**Comment by dmarcos** [comment]
I recommend creating a branch from `origin/master` and cherry-pick the relevant commits. You can open a PR from it afterwards:

```git checkout -b yourbranch origin/master
   git cherry-pick commit-hash
```

**Comment by dmarcos** [comment]
[PR example of your branch rebased on top of master](https://github.com/aframevr/aframe/pull/4734/files). Feel free to take it and reopen a new PR

**Pull request closed without merging**
