### PR TITLE
set ssl true for dev server for working webXR

### PR DESCRIPTION
**Pull request by arpu**
**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks. Not sure if SSL should be the default.

**Comment by arpu** [comment]
the only disadvantage is, developer has do allow the unknown ssl certification in the browser ( chrome and firefox will point to this after pageload)

**Comment by ngokevin** [comment]
webxr requires https even for localhost?

**Comment by arpu** [comment]
cannot test this
webxr compatible device is android phone or windows wmr 
(aframe is running on my fedora dev pc)

**Comment by dmarcos** [comment]
WebXR does *not* require HTTPS for localhost

**Comment by dmarcos** [comment]
I would make HTTP as a default and HTTPS as an option. `npm start https`

**Pull request closed without merging**
