### PR TITLE
v0.2.0 docs (fixes #949)

### LINKED ISSUE #949: Update 0.2.0 docs, guide

### PR DESCRIPTION
**Pull request by ngokevin**
**Docs:**

Dumping everything I know about A-Frame into these pages.

- [x] asset management
- [x] component API
- [x] components
- [x] entity API
- [x] primitives
- [x] scene
- [x] scene components
- [x] writing a component

**Guide:**

The previous guide was very unfinished. For the updated guide, I will condense into less pages such that each page is meatier and less sparse. I also nixed the "Entering VR" section and am going to point to [MozVR - Getting Started](http://mozvr.com/#start) instead to be less redundant.

- [x] Overview (what, who, why, how)
- [x] Getting Started (includes installation)
- [x] Building a Basic Scene (static, markup)
- [x] Building an Advanced Scene (use components, write components, create a game)

**Organization:**

- Guide - Overview, starting at the high-level
- Core - Start at the foundation
- Components - Build up
- Primitives - Back at the high-level

**Polish:**

- [ ] Embed codepens
- [ ] Typos
- [ ] Document ``````

### CODE REVIEW

**Comment by cvan** [comment]
Thanks for doing this. I know it was my original idea to have separate directories for each version's docs. And I know we talked about this in #950. I haven't thought of a better way, but I'm starting to get concerned about not being able to easily diff `0.1.0` from `0.2.0` docs. And what happens when we find a typo in `0.1.0` and we're at `0.7.0`? It'll become quite a pain to have to fix the corrections in every Markdown file in every directory. Though, it'd obviously be _way_, _way_ more difficult to cherry-pick typo fixes, re-tag things, etc.

Perhaps other projects have solved this issue? (I think not, but I'd love to be proved wrong.)

**Comment by ngokevin** [comment]
I'm planning on putting into the 0.2.0 directory. I just forgot to earlier today.

**Comment by ngokevin** [comment]
- I think there are tools to diff two directories, Git probably can do it. Even then, that's not a really common operation. 
- I really wouldn't bother fixing a typo six versions or even one version back. I'd only correct critical errors.

Let's optimize for the most major use case. When someone goes to aframe.io/docs, they see the latest version of the docs.

**Comment by cvan** [comment]
:+1:

**Comment by cvan** [comment]
are we wanting to do semver now?

**Comment by ngokevin** [comment]
Yeah, I think so. I'm taking inspiration from React since they're a big open source project. They just went from v0.14.0 to v15, and their reasons why influenced me to consider v1.0.0 over v0.2.0. I asked some people on Slack, and they agreed with either v1 or v2.

**Comment by cvan** [comment]
cool, I'm a fan

**Comment by ngokevin** [comment]
@cvan: @dmarcos said we should stick with 0-version as we don't want to imply stability or production-readiness. So gonna keep trucking to 0.2.0.

**Comment by ngokevin** [comment]
@cvan @dmarcos This is ready for review. Likely many typos and might have missed some content to note.

**Comment by ngokevin** [comment]
Thanks, can continue to address typos and comments and I can PR with a final draft

**Pull request merged**
