### PR TITLE
bump aframe-core to fix android shader bugs

### PR DESCRIPTION
**Pull request by ngokevin**
https://github.com/aframevr/aframe-core/pull/795

### CODE REVIEW

**Comment by ngokevin** [comment]
@cvan, will need assistance publishing the aframe-core package

**Comment by cvan** [comment]
okay, cool. in both places, we still need to bump dists, npm publish (which will create new tag which we need to push).

you should have access to these packages. if not, let me add you in a few min.

**Comment by ngokevin** [comment]
i don't have access, my NPM username is ngokevin, probably me@ngokevin.com

**Comment by cvan** [comment]
r+

**Comment by cvan** [comment]
want to update the CHANGELOG now?

**Comment by ngokevin** [comment]
bumped changelog. there is no travis on master so... :P

**Pull request merged**
