### PR TITLE
update mozilla logo in examples

### LINKED ISSUE #2443: Update Mozilla logo on Examples index
We ought to use the [new Mozilla logo](https://mozilla.ninja/) on https://aframe.io/aframe/examples/:

screen shot 2017-02-28 at 11 56 53 pm

### PR DESCRIPTION
**Pull request by pseuyi**
close #2443 update moz logo
- added the new logo and bumped up the size slightly in css to mirror old logo

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks! Can we line it up with the title?


screen shot 2017-03-05 at 3 41 58 pm

screen shot 2017-03-05 at 3 41 58 pm

screen shot 2017-03-05 at 3 42 04 pm

**Comment by pseuyi** [comment]
definitely~i'll look into it

**Comment by pseuyi** [comment]
updated~

**Comment by ngokevin** [comment]
Thanks! Still a bit off though. I use Page Ruler Chrome extension to line it up:

screen shot 2017-03-06 at 2 24 17 pm

screen shot 2017-03-06 at 2 24 08 pm

**Comment by pseuyi** [comment]
oh gotcha i wasn't using ruler. try now

**Comment by ngokevin** [comment]
Looks good, thanks!

**Pull request merged**
