### PR TITLE
Fixes camera issues under examples.

### PR DESCRIPTION
**Pull request by mkungla**
Removed misleading camera configurations under examples.
Surrounded cameras with entities where it was causing problems
under examples, like A-Frame Logo, Curved Mockups etc.

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks! It looks good. I want to make a round of test to all the examples before merging this.

**Comment by dmarcos** [comment]
@mkungla this needs rebase

**Comment by mkungla** [comment]
@dmarcos just rebased.

**Comment by dmarcos** [comment]
Thanks!

**Pull request merged**
