### PR TITLE
patches removeAttribute(`mixin`)

### PR DESCRIPTION
**Pull request by processprocess**
**Description:**
Allows entity.removeAttribute(`mixin`)

### CODE REVIEW

**Comment by ngokevin** [comment]
Awesome! The source code lives in `src/`, you can find it in `src/core/a-mixin.js`.

Would you be comfortable writing a unit test for that? `tests/core/a-mixin.js`

**Comment by takahirox** [comment]
Is this change good enough?
I think we should call `unregisterMixin` for all registered mixins for `removeAttribute('mixin')`.

(I was working on #2280 , too)

**Comment by processprocess** [comment]
@takahirox I see what you mean with that. I'm seeing how it can be approached with unregistering all mixins, then removing the mixin attribute.

@ngokevin it looks like a-mixin.js sets up the object initially, then mixin update logic is held in a-node.js. If we want to approach update logic in a-mixin.js, I wonder what the best approach is.

**Comment by ngokevin** [comment]
Needs some rebase and clean up of a bunch of comment and test code

**Comment by ngokevin** [comment]
Commited @ https://github.com/aframevr/aframe/commit/22c9ddb166c004d819f0d7c45f6cbb1e21e1fcf5

**Pull request closed without merging**
