### PR TITLE
add WebVR Origin Trial `<meta>` tags - for Chrome for Android (fixes #2405)

### LINKED ISSUE #2405: Enable origin trials so aframe site works on Chrome
https://github.com/jpchase/OriginTrials/blob/gh-pages/developer-guide.md

### PR DESCRIPTION
**Pull request by cvan**
* create standalone `preghpages` script
* replace shell-related dependencies w/ shelljs + shx

### CODE REVIEW

**Comment by dmarcos** [comment]
It looks good to me if it works on Windows. Has anybody tried?

**Comment by cvan** [comment]
> It looks good to me if it works on Windows. Has anybody tried?

The WebVR Origin Trials have been and will continue to be for only Android.

It's confusing, but there are two active WebVR Origin Trials (because they needed to extend the trial, and they're not allowed to "extend" trials; they have to create new trials, since they're supposed to be contained experiments with an expiry date).

Anyway, you can see the list of active Origin Trials on [this page](https://github.com/jpchase/OriginTrials/blob/gh-pages/available-trials.md#current-experimental-features):

> **Timeline**
> WebVR
>
> First available in Chrome M56. Trial ends on June 13, 2017.

> **Feature**
> WebVR (For Chrome M59+)
>
> **Timeline**
> First available in Chrome M59. Trial ends on October 17, 2017.

Chrome for Windows is currently at M58 (released May 2, 2017), and according to Brandon's March 29 [`blink-dev` post](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/OnZVNSGwEFU), there are no plans yet for a WebVR Origin Trial on other platforms:

> Will this feature be supported on all five Blink platforms supported by Origin Trials (Windows, Mac, Linux, Chrome OS, and Android)?
> The WebVR API will be available on Android only for the M59. Work to expose the API to Windows is underway, but the exact timeframe is unknown. Other platforms can be supported in the future, but at this time there is no significant VR hardware at this time that supports Mac, Linux, or Chrome OS. We do intend to evaluate support on any platforms that gain VR hardware support in the future.

I've documented the Origin Trial info. on WebVR Rocks for [Chrome for Android](https://webvr.rocks/chrome_for_android#what_is_the_webvr_origin_trial), but I'll also document this for [Chromium/Chrome for (Windows) desktop](https://github.com/WebVRRocks/webvrrocks/issues/237).

**Comment by dmarcos** [comment]
I was referring to the new gh-pages script

**Comment by dmarcos** [comment]
I just tried. It seems to work. Thanks!

**Comment by cvan** [comment]
np, thank you 👍

**Pull request merged**
