### PR TITLE
organize examples (fixes #1247)

### PR DESCRIPTION
**Pull request by ngokevin**
**Changes proposed:**

- Folders.
- Move asset into the folder of the example they are being used in.
- Put very-commonly used assets in the root `assets/` folder.
- Remove unused assets.
- Remove unnecessary example (i.e., `controls`) that are prevalent throughout all the other examples.
- `s/stats="true"/stats/g`
- Use asset management system when possible

### CODE REVIEW

**Comment by dmarcos** [comment]
I want to keep mixin and controls examples. I use them all the time for testing and I've caught more than one bug with them.

**Comment by dmarcos** [comment]
They are also useful to illustrate the feature with no other noise

**Comment by ngokevin** [comment]
I won't argue for mixin. Do you really need controls? Every single example will have controls guaranteed.

**Comment by dmarcos** [comment]
It makes me happy to see all those underscore directory names gone :)

**Pull request merged**
