### PR TITLE
[collada-model] Deprecate 'collada-model'.

### PR DESCRIPTION
**Pull request by donmccurdy**
Per https://github.com/aframevr/aframe/issues/3793. 

What do you think of just marking it deprecated for a release before we remove anything? Or better to just go for it?

### CODE REVIEW

**Comment by ngokevin** [comment]
I'm okay just going for it. I haven't seen COLLADA use, and many of the popular asset places don't export them now. Also need to remove from examples.

**Comment by ngokevin** [comment]
I think realistically 2-3 weeks.

**Comment by dmarcos** [comment]
Happy to remove it. 0.9.0 is a good heads up before 1.0.0 when we should consolidate to glTF.

**Comment by ngokevin** [comment]
@donmccurdy Want to execute the removal? Also want to have a go at reviewing some of my recent PRs?

**Comment by donmccurdy** [comment]
I'm working on the `collada-model` removal now. I think it will require merging something like #3757 to keep consistent colors, as we replace the `.dae` examples with `.glb`. #3757 is still waiting for me to make changes at this point too I think. 😅

**Comment by ngokevin** [comment]
Going with https://github.com/aframevr/aframe/pull/3866

**Pull request closed without merging**
