### PR TITLE
fix for transparency issue with png images

### PR DESCRIPTION
**Pull request by js-d-coder**
https://github.com/aframevr/aframe/issues/666#issuecomment-302831463

### CODE REVIEW

**Comment by donmccurdy** [comment]
+1 for mentioning this, although I might clarify it a bit:

> When using PNG images as cutouts or masks (where part of the image should be fully transparent, and the rest fully opaque), use `transparent=false` and set `alpha-test` to something like 0.5.

**Comment by dmarcos** [comment]
@js-d-coder This almost ready. Are you incorporating the changes that @donmccurdy suggested?

**Comment by ngokevin** [comment]
Would also use `material="alphaTest: 0.5"` versus the primitive form.

**Comment by ngokevin** [comment]
Will address comments in follow up commit.

**Pull request merged**
