### PR TITLE
Remove various polyfills

### PR DESCRIPTION
**Pull request by mrxz**
**Description:**
This PR removes the polyfills that should only really impact IE11 (or other older browsers). See #5447 for context.

**Changes proposed:**
- Remove `@ungap/custom-elements`, `present`, `promise-polyfill` and `custom-event-polyfill`
- Remove `String.startsWith` polyfill
- Replace `object-assign` ponyfill with `Object.assign`

### CODE REVIEW

**Comment by dmarcos** [comment]
@WebReflection Do you think the we should still keep the custom elements polyfill around? I'm sure he has a more complete picture than me.

**Comment by WebReflection** [comment]
> @WebReflection Do you think the we should still keep the custom elements polyfill around? I'm sure he has a more complete picture than me.

If you don’t use builtin extends and you don’t use the argument in whenDefined resolved promise I think the time to drop that polyfill might be right but I’d rather check dependent projects as they might assume a-frame provides the polyfill and might trust those features so that it might break others.

**Comment by dmarcos** [comment]
Thanks both for the work and the feedback 👏

**Comment by WebReflection** [comment]
> It probably suffices to mention it in the release notes, along with instructions on including the polyfill manually for those affected by the change.

Absolutely, my comment was rather about the fact I *think* dropping polyfills *should* be considered a breaking change or nothing less than a minor release (but as it could break, maybe breaking change is more appropriate, semver speaking).

If you think the risk is minimal though and this library users won't be affected, a note is likely all you need 👍

**Pull request merged**
