### PR TITLE
Fixed link components image being flipped horizontally

### PR DESCRIPTION
**Pull request by greengiant83**
Link Component

Fix for issue 3077 https://github.com/aframevr/aframe/issues/3077
Flipped the sign on sampleUV.x in the Portal shader that is used by the link component

### CODE REVIEW

**Comment by greengiant83** [comment]
This is my first pull request, so if I did something particularly bone headed, please let me know. 
This should be a single character change to src/components/links.js

**Comment by greengiant83** [comment]
I will if I can figure out how to do that

**Comment by greengiant83** [comment]
Not sure if it was the best way to handle it, but I sent a new pull request with just that file changed. https://github.com/aframevr/aframe/pull/3079

**Comment by dmarcos** [comment]
Closing in favor of https://github.com/aframevr/aframe/pull/3079

**Pull request closed without merging**
