### PR TITLE
Make textures POT (fixes issue #300)

### PR DESCRIPTION
**Pull request by cemkod**
Resized texture images to powers of ten.

### CODE REVIEW

**Comment by ngokevin** [comment]
awesome, thanks! will take a look in a bit

**Comment by cemkod** [comment]
This is my first pull request for a public project. Hope I have done everything right.

**Comment by ngokevin** [comment]
everything looks great except for the MozVR text. In the shopping example, it looks a bit low-res. Can we upscale rather than downscale that one?

**Comment by cvan** [comment]
first off, many thanks or taking this on! much appreciated :+1:

could you change your commit message from `Make textures POT (Issue: #300)` to `Make textures POT (fixes issue #300)` - so that issue #300 gets automatically closed when this PR gets closed?

also per @ngokevin, these in particular I noticed the images are upscaled (with degradation) and there is padding around the increased images:

[examples/_images/mozvr.png](https://github.com/aframevr/aframe/pull/312/files#diff-02a70a894c5875f35c6a967f36a64524)
[examples/_images/webvr.png](https://github.com/aframevr/aframe/pull/312/files#diff-2525e623c11e254dcb2eb89452835637)
[examples/_models/tree2/tex/shadow-circle.png](https://github.com/aframevr/aframe/pull/312/files#diff-ef7c149f83680eb4d220e43f0b4fb2e9)
[examples/showcase-composite/portland.png](https://github.com/aframevr/aframe/pull/312/files#diff-8802048f80398add331bff00a56e96a9)
[examples/showcase-shopping/price.png](https://github.com/aframevr/aframe/pull/312/files#diff-a2fbee1d60bed01576109439cd96436d)
[examples/showcase-shopping/shoes.png](https://github.com/aframevr/aframe/pull/312/files#diff-d64d04822557afb3a361c1b901fc18cc)

most of the rest of them (e.g., [`examples/showcase-anime-UI/images/glow1.png`](https://github.com/cemkod/aframe/blob/make-textures-pot/examples/showcase-anime-UI/images/glow1.png)) look downscaled okay without excess padding created.

**Comment by ngokevin** [comment]
fwiw the increased padding seems accounted for by changing positions.

**Comment by cemkod** [comment]
I tried to fix the positioning and aspect ratios of all materials in the examples according to the changed dimensions. It is not possible to convert the textures to POT and not add a padding in some cases because some of the examples contain textures with dimensions that are not integer divisible (as in: 1/2 ,1/4 as opposed to 1/1.35). If the image is scaled so that one dimension is a power of two, the other dimension is not so some padding has to be added.

How do I change the commit message in github? Is it possible to change history?

**Comment by ngokevin** [comment]
thanks!

**Pull request merged**
