### PR TITLE
Add webxr referenceSpaceType schema entry and documentation

### PR DESCRIPTION
**Pull request by klausw**
**Description:**
Support changing the scene reference space to something other than 'local-floor'

**Changes proposed:**
- add schema entry
- use the name in webxr-tracked-controller and in three.js (for the viewer pose)
- update documentation

### CODE REVIEW

**Comment by dmarcos** [comment]
There's a failing test but I think is a travis issue.

**Comment by klausw** [comment]
I've changed the laser-controls test to use "local" reference space to test this, here's a live version: https://klausw.github.io/aframe/examples/test/laser-controls/

I've tried it on Chrome using Daydream View and AR on Android, and SteamVR on Windows. It looks like the head and controller positions are consistent with each other with this change included.

**Comment by dmarcos** [comment]
Thanks!

**Comment by dmarcos** [comment]
Awesome work! Thanks!

**Pull request merged**
