### PR TITLE
shrunk width and height for box/plane to 1 #1197

### PR DESCRIPTION
**Pull request by bryik**
Changed geometry.js and amended docs

### CODE REVIEW

**Comment by dmarcos** [comment]
Nice! Can you squash your commits?

**Comment by bryik** [comment]
Noticed additional changes to make aside from geometry.md, want to make sure I didn't miss anything else

**Comment by ngokevin** [comment]
What happened to this?

**Comment by bryik** [comment]
Sorry, I'm new at this (have only used Mercurial solo in the past). I thought I'd close it, then reopen after I fixed the commits on my repo. I guess it doesn't work that way?

**Comment by ngokevin** [comment]
You don't have to close it. Just force-push to the branch and the pull request will update. I guess now you can just re-open or open a new one.

**Comment by bryik** [comment]
I can't re-open, so I'll open a new one. Thanks for the help!

**Pull request closed without merging**
