### PR TITLE
Added a template repo for gTLF in React.js apps

### PR DESCRIPTION
**Pull request by rand0mC0d3r**
**Description:**
Added a link to a sample React.JS project that shows how to load correctly a gTLF file from the Google Poly API. The project is simple and self explanatory and can be plugged with any other API or locally loaded resource

**Changes proposed:**
- Adding a link to a template like project for React developers to load simply a gTLF file along with it's assets
- Reffered project is self explanatory and is modern and simple for newbies coming from a WebDevelopment towards a 3d/xr world

**Why Google Poly**
- Because loading assets from a server is a default business scenario path and handling render cycles in a declarative A-Frame is currently not covered in a simple reproducible way.

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks. We discourage combining A-Frame and React. While workable there are negative performance implications (react is good but designed for different purposes)

**Comment by rand0mC0d3r** [comment]
Hello Diego & thanks for the answer. In hindsight you are right to close it. But I want to take this chance to ask how can Non-3d developers build a bridge towards A-Frame? 

I mean...3D was never really mainstream and was only in Blender/Maya/.., and gaming and the other heavy apps. Now coming to the web and having WebAPI support opens a lot of shops, business ideas, dashboard representations and so. Out there is a big community that did a big part of they're employment work with 1-2 frameworks, like Angular, Vue or React.

In order to help push this forward, i would like to propose/recommend some sort of section for integrations/bridges. In west Europe there is a big interest in VR/AR to come into furniture and custom products, and 3d printing customized products, where a lot of jobs are towards putting a VR viewer as a hot replacement for an old image gallery, but those need training and examples.

Can i help you help others/us build a page, or - i am open to any idea, where we can share this and make it accessible? 

Looking forward to your answer. thanks

**Comment by dmarcos** [comment]
You are more than welcome to publish and share a list of resources on social media, personal blog, Slack, Discord... The community will appreciate. Having such a list on the A-Frame docs adds a lot maintenance burden. It’s very hard to keep track of the state of all projects and info gets quickly obsolete.

**Comment by arpu** [comment]
@dmarcos  is this still a problem with react? i use ``React.PureComponent ``` with aframe heavily and see no perf problem

**Comment by rand0mC0d3r** [comment]
Out of all PureComponent is the heaviest. Functional components have the least penalty if you just use the A-frame as a end of chain component when rest of the state is settled across. my 2 cents

**Pull request closed without merging**
