### PR TITLE
bump threejs to 0.98.0

### PR DESCRIPTION
**Pull request by arpu**
threejs 98r release  have some nice  Webvr commits like

https://github.com/mrdoob/three.js/pull/14950

tested on my private project without any problems

**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by arpu** [comment]
fixes #3775

**Comment by ngokevin** [comment]
Can someone compile a list of breaking changes? Bumping three.js usually comes with its breakages.

**Comment by arpu** [comment]
https://github.com/mrdoob/three.js/wiki/Migration-Guide

**Comment by arpu** [comment]
it looks like there is a smal problem with PositionalAudio on Chrome after this merge https://github.com/mrdoob/three.js/pull/15151

if i have a normal a-sound component and a PositionalAudio  the sound is sometimes  choppy
works on revert

**Comment by dmarcos** [comment]
Closing this in favor of https://github.com/aframevr/aframe/pull/3875 We will need r98 + a couple of commits needed for WebXR support

**Pull request closed without merging**
