### PR TITLE
fix timestamps when timeDelta is implausible

### PR DESCRIPTION
**Pull request by machenmusik**
Make sure time doesn't go backwards, and that deltas are reasonable.

Experimental versions of Chromium used for WebVR have a known issue
where the requestAnimationFrame timestamp is off by 1000
(microseconds instead of milliseconds)

### CODE REVIEW

**Comment by machenmusik** [comment]
This is a more thorough solution to the issue behind #2208

**Comment by dmarcos** [comment]
I would not prefer to introduce work around for browser bugs. Specially when those bugs are known and come from experimental builds

**Comment by machenmusik** [comment]
On the one hand, I understand entirely this sentiment.  (Although personally I prefer this one as it makes all A-Frame `tick` handling immune to stupid time behavior, not the specific off-by-1000 Chromium bug.)

On the other hand, the experimental builds are the only ones with native Oculus support, are commonly used for both Rift and Vive WebVR development, and are currently susceptible to loss of controller updates...  as it is not an A-Frame bug, I am not sure we want this to break loudly in QA vs. writing a `warn` message to logs and continuing on.  If you prefer to switch `tracked-controls` support to use `throttle` rather than `throttleTick`, rather than introducing workarounds into either `throttleTick` or the core itself, I can make a PR for that, but I don't think we should just leave things broken as-is.

**Comment by dmarcos** [comment]
Chromium experimental builds are not the only ones with native Oculus and Vive support. Firefox Nightly also supports both.

**Comment by machenmusik** [comment]
> Firefox Nightly also supports both.

Really?  when I run Nightly, it only supports Oculus via SteamVR, so Touch controllers show up as OpenVR Gamepads and lose many of their unique characteristics...?

**Comment by machenmusik** [comment]
> If you prefer to switch tracked-controls support to use throttle rather than throttleTick, rather than introducing workarounds into either throttleTick or the core itself, I can make a PR for that, but I don't think we should just leave things broken as-is.

I think we are pretty close to done on #2192, if you prefer I can add the change from `throttleTick` to `throttle` in that PR

**Comment by dmarcos** [comment]
Nightly supports Oculus Rift natively but not Touch yet. We're days away from having support for touch. I insist on my preference of not accumulating workarounds in the code base for known bugs in one off experimental builds of a specific browser.

**Comment by machenmusik** [comment]
OK, understood.  I will change `throttleTick` to `throttle` as part of #2192 and close this PR

**Pull request closed without merging**
