### PR TITLE
merge aframe-core into aframe

### PR DESCRIPTION
**Pull request by ngokevin**
Proposed steps:

1. Merge `aframe-core` into `aframe` dev branch (this PR). For now, aframe-core + elements will all be in one build.
2. Extract custom elements code to `aframe-primitives` package and repository.
3. Have the new `aframe` repository create several builds: `aframe-core.js` and `aframe.js`. `aframe.js` will be a **kit** build that will import things such as `aframe-primitives`. The core build will be similar to what we have today, but it will register itself to the namespace as `AFRAME`.
4. Continue to advertise and distribute the kit build. `npm install aframe` will still have everything.
5. Modify documentation.
6. Release.
7. Remove `aframe-core` repo. 

This should satisfy everyone:

- The `aframe` build will still continue to have things out of the box for newcomers.
- The `aframe-core` build will be minimal for people that don't want the extra stuff.
- No more confusion between `aframe` and `aframe-core`.
- Technically, this creates clean layers of separation.
- Usability-wise, people still receive abstracted layers.

Commands used:

```bash 
git remote add core ~/Code/aframe-core
git fetch core
git merge core/dev
# Then fix merge conflicts such as package.json, budo.js, README.md, etc.
```

### CODE REVIEW

**Comment by ngokevin** [comment]
r? @cvan 

This fulfills Step 1 of the proposal in the description. If everyone agrees on the general direction, we can work on extracting elements/primitives to a different repository, and then including it into the aframe bundle from here.

**Comment by ngokevin** [comment]
Or @dmarcos

**Comment by dmarcos** [comment]
What do we do with the issues on the core repo?

**Comment by dmarcos** [comment]
and with the issues in this repo?

**Comment by ngokevin** [comment]
We can use: https://github.com/IQAndreas/github-issues-import to migrate issues from to `aframe`.

**Comment by ngokevin** [comment]
Hoping to merge this today so I can keep working on repo cleanup.

**Comment by ngokevin** [comment]
@dmarcos and I are planning on coordinate this tomorrow. We'll merge the repos and switch development over in one swoop.

**Pull request closed without merging**
