### PR TITLE
accommodate VR presentation changes for WebVR v1.0 API

### PR DESCRIPTION
**Pull request by cvan**
Tested in

* latest Chromium builds
* old deprecated Chromium builds on Mac
* Firefox Nightly on Windows
* Firefox Nightly on Mac
* Safari on iOS
* Firefox stable on Mac
* Firefox stable on Windows
* Chrome stable on Windows
* Chrome stable on Mac

Opened up a PR against three.js to fix several things in `VREffect`: mrdoob/three.js#8330

Needs testing + help in

* Firefox for Android
* Chrome for Android

I tried for quite a while but the remote debugging workflow was a PITA and I kept getting weird issues. Anyway, on Android, stereo upon clicking the "Enter VR" button is not working and some resize issues have been introduced. I don't yet know if they're related to pieces of A-Frame I've touched, `VREffect`, or latest `webvr-polyfill` w/ WebVR 1.0 API changes. Help needed!

### CODE REVIEW

**Comment by masom** [comment]
Chrome on Android ( Moto X 1st gen ) works!

**Comment by masom** [comment]
Just got a report it's not working on iPhone 6S

**Comment by masom** [comment]
On Android, stereo upon clicking the "Enter VR" button is not working

Worked for me o_O

**Comment by dmarcos** [comment]
@masom Thanks for helping

**Comment by dmarcos** [comment]
Travis complains

**Comment by K4orta** [comment]
I tested Chrome 48.0.2564.95 on Android (Nexus 5x) and entering VR caused the app to go full screen, but no stereo.

On Firefox 45.0 for Android, entering VR caused a crash report dialog. Still trying to figure out if I can get a stack trace from the example before it goes down.

**Comment by dmarcos** [comment]
@K4orta Thanks for testing this

**Comment by cvan** [comment]
thanks, y'all. any help with figuring out how to get Android (and all other browsers) to play nicely when

* `navigator.getVRDisplays` is polyfilled by webvr-polyfill
* `navigator.getVRDevices` is polyfilled by webvr-polyfill
* `navigator.getVRDisplays` is natively supported
* `navigator.getVRDevices` is natively supported

https://github.com/cvan/three.js/blob/fix-vreffect-safari/examples/js/effects/VREffect.js
https://github.com/mrdoob/three.js/pull/8330/files

https://github.com/borismus/webvr-polyfill/issues/41 would help identify more reliably whether the interfaces are polyfilled.

thoughts with the `VREffect` changes?

**Comment by pushmatrix** [comment]
Any progress on this? I'm noticing that on my iPhone 6S the latest aframe does not do splitscreen.

**Comment by ngokevin** [comment]
I think there will be more progress this week as the team gets back together. This PR is high priority.

**Comment by cvan** [comment]
branch updated. sorry for the delay, folks. currently, there are quite a few changes/regressions with `THREE.VREffect` and [webvr-polyfill](https://github.com/borismus/webvr-polyfill) that need to be resolved. also, the 1.0 API implementation in the Chromium builds is _very_ buggy and unreliable, but I'm glad it exists. so, I'm experiencing a lot of WebGL crashes, and the logs are cryptic (to me at least). anyway, could use some help with this. @ngokevin, do you have some cycles early next week to help?

**Comment by ngokevin** [comment]
yes

**Comment by dmarcos** [comment]
I've tried this PR with on Chromium WebVR 1.0 + CV1 + Windows 10. Android and iOS. The only weird thing I've seen is that Android does not trigger stereo mode. @cvan Is that the only thing that was missing?

**Comment by dmarcos** [comment]
@cvan Do you have a list of the open problems on the VREffect/VRControls/WebVR-polyfill front?

**Comment by dmarcos** [comment]
Do we need to import all the individual files of the webvr-polyfill? We can just use the dist/bundle? I've realized that webvr-polyfill imports the three.js Math library. We could cut its size in more than half if we build the polyfill to use the THREE math we already have in aframe.

**Comment by dmarcos** [comment]
I close this in favor of https://github.com/aframevr/aframe/pull/1423
@cvan can you provide feedback

**Pull request closed without merging**
