### PR TITLE
Added type=color to schemas

### PR DESCRIPTION
**Pull request by fernandojsg**
**Description:** Explicitly added ```type='color'``` for every color parameters in the components' schemas.

### CODE REVIEW

**Comment by ngokevin** [comment]
Want to make the default value of the `color` property type, `#FFF`? Then we can simply do `{type: 'color'}`.

**Comment by fernandojsg** [comment]
Yes, I think ```#FFF``` could be nice as default.

**Comment by dmarcos** [comment]
is white a nice default or better a color that pops out so it's useful for debugging?

**Comment by ngokevin** [comment]
If you have a different default, then every mesh with a texture you have to define white, else the color will blend with the texture.

**Comment by fernandojsg** [comment]
Yep, and also in the lights you will need to change to white too

**Comment by ngokevin** [comment]
We can change here, and then that will be the default default: https://github.com/aframevr/aframe/blob/master/src/core/propertyTypes.js#L11

**Comment by dmarcos** [comment]
let's do white as default then.

**Pull request merged**
