### PR TITLE
add `selectorAll` property type, fix #1049

### LINKED ISSUE #1049: add `selectorAll` property type
Similar to `selector` property type.

Add the convenience of converting the NodeList to an array

### PR DESCRIPTION
**Pull request by legendtang**
yeah, the third time :0

### CODE REVIEW

**Comment by ngokevin** [comment]
Can you squash your two commits into one?

**Comment by legendtang** [comment]
@ngokevin Shall rebase soon.

**Comment by legendtang** [comment]
All cleared.

**Comment by dmarcos** [comment]
Thanks! Good work!

**Pull request merged**
