### PR TITLE
Update hand-tracking-grab-controls.js

### PR DESCRIPTION
**Pull request by addy1997**
changed function name from **tock** to **tick**

### CODE REVIEW

**Comment by dmarcos** [comment]
Is there any problem with the tock function?

**Comment by vincentfretin** [comment]
Why? In case you didn't know, it's not typo, you can create a tock method on a component, that is invoked after the scene has rendered.

**Comment by addy1997** [comment]
Sorry! @dmarcos. I thought that tick was the default function. Hence, this PR. I'll close it

**Comment by dmarcos** [comment]
No problem. To be honest my `tock` is a bit sloppy. Started with a `tick` but was getting some object position updates lagging behind by one frame. `tock` seemed to fix it but didn't fully understand why. So your PR might make sense in the future :)

**Pull request closed without merging**
