### PR TITLE
Merge pull request #1 from aframevr/master

### PR DESCRIPTION
**Pull request by ttepperg**
Merged from origin

**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by jure** [comment]
Hey @ttepperg, this looks like an erroneously opened PR, as it contains no changes. Maybe you selected the wrong branches? It looks like you opened a PR on your fork to update it from latest upstream master - so perhaps this one was just opened by mistake.

**Comment by ttepperg** [comment]
Hi Jure,

Yes, my mistake and my most sincere apologies. Can you disregard this PR
from your side or do I need to cancel it?

Kind regards

Thor

**Comment by jure** [comment]
No worries, Thor! I’m not a maintainer of this project, so I can’t close it - but closing from your end is the right way to do it anyway.

**Comment by dmarcos** [comment]
Closing this. Notice you should also be able to close the PR

**Comment by dmarcos** [comment]
Closing this. Notice you should also be able to close the PR

**Comment by ttepperg** [comment]
Thanks, Diego

**Pull request closed without merging**
