### PR TITLE
merge dev into master (fixes #972)

### LINKED ISSUE #972: remove dev/master workflow
Every time someone makes a PR then, it will auto-target the `dev` branch.

### PR DESCRIPTION
**Pull request by ngokevin**
- Added `aframe-v0.1.2.js` builds to `dist/`
- The current `aframe.js` builds are "nightly", we will automate bumping those often

### CODE REVIEW

**Comment by dmarcos** [comment]
Hold on a bit until some of the pending PRs land.

**Comment by ngokevin** [comment]
PRs can be cherry picked to master

**Comment by ngokevin** [comment]
I think PRs are going to keep piling in. Should we do this sooner? Patches that land can be picked to master pretty easily.

**Comment by ngokevin** [comment]
Guess we just do this when we launch.

**Pull request closed without merging**
