### PR TITLE
Update camera.js

### PR DESCRIPTION
**Pull request by karansaulakh**
**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by dmarcos** [comment]
@karansaulakh Why do you prefer a 0.05 value?

**Comment by ngokevin** [comment]
I forgot why the default user height for the bare camera component is 0 and not 1.6?

**Comment by dmarcos** [comment]
Because a camera can be used for anything not just for a human scale avatar. You might want to use the camera on a plane cockpit or on a car driver seat post. The camera should be scale agnostic and other higher level components should introduce the concept of scale, avatar or player

**Comment by ngokevin** [comment]
The default camera and `<a-camera>` have a 1.6m default, shouldn't the camera component? The camera can be used for anything, but a standing human seems like a reasonable default versus clipping the ground.

**Comment by dmarcos** [comment]
Adding magic offsets is always confusing. I would probably rename `<a-camera>` to `<a-player>` or `<a-avatar>` or something like this. I prefer to keep the camera component agnostic

**Comment by ngokevin** [comment]
Ok, will close

**Comment by machenmusik** [comment]
agree with @dmarcos also see #2265

**Pull request closed without merging**
