### PR TITLE
don't bubble state events

### PR DESCRIPTION
**Pull request by ngokevin**
**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by wmurphyrd** [comment]
I use state event bubbling quite a lot for advanced interactions using super hands. For example, a selectable component which listens for state end events coming from the grabbed or clicked states of any if its children to keep track of the last selected child.

**Comment by dmarcos** [comment]
What's the rational to not bubble state events?

**Comment by machenmusik** [comment]
I assume it is performance, but if we're not going to bubble them (which is kinda the point of using events for that IMO), then maybe you want to consider removing and reimplementing...

**Comment by ngokevin** [comment]
It was for performance and semantics. For my laptop, a stateadded or stateremoved call each take ~.1ms (1% of a 90FPS budget), didn't quite like the cursor used it, so figured I could ameliorate it a bit. I thought it didn't make sense to bubble these events when they are very single-entity-specific.

I could go either way, my full desire would be to remove the API, and just use the cursor events provided. Second would be to remove event bubbling so it doesn't fire on like 10+ ancestors. If there's disagreement, don't mind closing either.

**Comment by dmarcos** [comment]
When I write that API bubbling was what made it valuable. I used it to have a bunch of entities (created dynamically) changing to a specific state (`dead`) that I wanted to get notified for. Maybe we don't bubble but emit also on the scene so one can attach a single listener? @wmurphyrd Would that work for you?

**Comment by ngokevin** [comment]
Closing for now, but recommend to switch components to use events.

**Pull request closed without merging**
