### PR TITLE
increased default segments for other round primitives

### PR DESCRIPTION
**Pull request by roninb**
Should close up issue #1216. Increased default segmentsTheta and segmentsTubular to make round primitives more round (or smooth).

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks! Can you do segmentsPhi as well?

**Comment by roninb** [comment]
segmentsPhi is actually how many triangles are rendered per SegmentsTheta (how many segments built for each trapezoid (?) that makes up the ring) so it doesn't make the circle more round, at least according to the docs.

**Comment by ngokevin** [comment]
Aye, good catch.

**Comment by ngokevin** [comment]
Future ref, you can append commit message with ```(fixes #ISSUENUMBER)``` so that issue auto closes on merge

**Comment by cvan** [comment]
@ngokevin as I discovered, it'll auto-close the issue only if the author is added as a ["Collaborator"](https://github.com/aframevr/aframe/settings/collaboration) to the project. I wish GitHub did that automatically.

**Comment by ngokevin** [comment]
As long as it's in the PR message when one of us merges it, it'll close.

**Comment by roninb** [comment]
Thanks for the heads up, I'll make sure to remember that next time!

**Pull request merged**
