### PR TITLE
use webvr-polyfill version that handles missing rotationRate

### PR DESCRIPTION
**Pull request by machenmusik**
**Description:**
Fixes log spam due to missing rotationRate observed on newer iOS.
**Changes proposed:**
Use fixed webvr-polyfill (which in turn uses fixed cardboard-vr-display)

### CODE REVIEW

**Comment by dmarcos** [comment]
Head orientation on stereo mode via polyfill is currently broken on latest iOS 13.4.1 Does this fix the issue?

**Comment by machenmusik** [comment]
I don't know, but quite possibly - was going to suggest that on the issue and reopen it

**Comment by andreyrd** [comment]
This prevents the page from crashing because of the log spam, but it does not make orientation work again.

And it also relies on referencing specific branches of a forked repository..to two levels.
Ultimately it needs to be fixed way upstream in https://github.com/immersive-web/cardboard-vr-display.

**Comment by dmarcos** [comment]
The issue has been fixed upstream in the webvr-polyfill repo thanks to @jsantell. Now merged in master. Thanks everybody for investigating

**Pull request closed without merging**
