### PR TITLE
Incorrect labelling of HTML tag in the image

### PR DESCRIPTION
**Pull request by ShaguftaMethwani**
**Description:**
- The closing tag of HTML is labelled as the 'Opening tag'

**Changes proposed:**
- A different image with correct labels

### CODE REVIEW

**Comment by ngokevin** [comment]
I think the image looks fine, img doesn't need a closing tag and your image is served straight from raw.git which isn't a cdn

**Comment by ShaguftaMethwani** [comment]
It was in the a-box tag, but yes not a cdn. Nevermind.

**Comment by ngokevin** [comment]
Oh, I see.

**Comment by ngokevin** [comment]
Oh, I see! Sorry. That looks great. If you drag your image into any GitHub issue / pull request comment box, it will upload to CDN.

**Comment by ShaguftaMethwani** [comment]
Sure. uploaded here. 
baf101da-29e7-11e7-82c4-b0ac3903e667

**Comment by ShaguftaMethwani** [comment]
I'll change the url

**Comment by ngokevin** [comment]
Thanks! Nice image editing work

**Pull request merged**
