### PR TITLE
add system attribute caching (fixes #4753)

### LINKED ISSUE #4753: System failed to cache attribute
**Description:**
System failed to cache attribute

seems like there is TODO in `src/core/system.j`

``` javascript
 * TODO: Have the System prototype reuse the Component prototype. Most code is copied
 * and some pieces are missing from the Component facilities (e.g., attribute caching,
 * setAttribute behavior).
```
- A-Frame Version: 1.1.0
- Platform / Device: Chrome 87.0.4280 (Mac OS X 11.0.0)
- Reproducible Code Snippet or URL: https://github.com/aframevr/aframe/blob/cfd869b271cef9454e0c7979af1fb59c880194bc/src/core/system.js#L23-L25

### PR DESCRIPTION
**Pull request by ryanaltair**
**Description:**
Fixes #4753 
**Changes proposed:**
- implement system setAttribute with caching (like component)
- add unit test `for can update system with setAttribute with cache` in `tests/core/system.js`

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks! It would be better for component / system to use the same prototype vs. duplicating logic as stated in the [TODO](https://github.com/aframevr/aframe/blob/cfd869b271cef9454e0c7979af1fb59c880194bc/src/core/system.js#L23-L25)

**Comment by ryanaltair** [comment]
Confirm and agree. I will refactor them later. @dmarcos

**Comment by ryanaltair** [comment]
from now, all systems register to AFRAME with (`AFRAME.registerSystem()` )will init and add to sceneEl, even the sceneEl never has these system attributes in DOM.

**Review by ricohydent — APPROVED** [review]

**Comment by ryanaltair** [comment]
hi @dmarcos , I remove the TODO and add a [base prototype](https://github.com/xuelang-group/aframe/blob/dev_add_system_missing_func/src/core/base.js) for component and  system.

**Pull request closed without merging**
