### PR TITLE
bump wakelock

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by cvan** [comment]
r? @ngokevin @dmarcos @caseyyee 

image

**Comment by ngokevin** [comment]
lgtm if you think it will help

**Comment by caseyyee** [comment]
just FWIW, Wakelock doesn't work properly with FF Android.    It won't take the base64 encoded video for some reason.   Should work everywhere else though.

Besides that looks good to me!

**Comment by cvan** [comment]
going to open a separate PR that actually fixes #875

**Pull request closed without merging**
