### PR TITLE
isMobileVR distinguishes Samsung Internet for Gear VR from Samsung Internet for Android

### PR DESCRIPTION
**Pull request by DougReeder**
**Description:**
Fixes issue #4187
https://github.com/aframevr/aframe/issues/4187

**Changes proposed:**
Samsung Internet for Gear VR has "Mobile VR" in the useragent where Samsung Internet for Android has "Mobile", so the existing regex clause that checks for `Mobile VR` will return true for the Gear VR version and false for the Android version.
-
-

### CODE REVIEW

**Comment by dmarcos** [comment]
The test would return false for Go / GearVR versions of Samsung Internet. We need a different way to discriminate. What's the complete userAgent string for Samsung Internet in Go / GearVR?

Side note. We don't submit A-Frame builds as part of PRs

**Comment by DougReeder** [comment]
Format of userAgent matches https://developer.samsung.com/internet/user-agent-string-format for devices I can test, with $(UX RECOMMEND) being "Mobile" on Android and "Mobile VR" on Gear VR.

I don't have a Go to check what it is there.

**Comment by dmarcos** [comment]
Thanks. it looks good if we can verify that the function returns true in Oculus Go. 

Can you remove the dist and index.js files from the PR?

**Comment by dmarcos** [comment]
Thanks. it looks good if we can verify that the function returns true in Oculus Go for Samsung Internet.

Can you remove the dist and index.js files from the PR?

**Comment by dmarcos** [comment]
Thanks

**Pull request merged**
