### PR TITLE
[WIP] Updated dependencies related to #1635

### PR DESCRIPTION
**Pull request by mkungla**
I have tested these updates fairly extensively. Failed to update three to 0.79 because of failing tests on textures and material

### CODE REVIEW

**Comment by dmarcos** [comment]
Update three.js dependency is definitively due.

**Comment by dmarcos** [comment]
I believe dependency update has to be deliberate: why do we want to update?

**Comment by mkungla** [comment]
@dmarcos Better to do it now than later. As aframe is running for 0.4.0 many new futures will be added! Right? As currently there are long time warnings for some deps. about to become deprecated. while now you already see warnings that your deps will stop working since their deps will not be included in future releases etc. I find that this is a must that at the beginning of next version roadmap you update your deps and solve any exposed issues before you start building new futures on top of something which may not work anymore when you finally to the update. Another point here is that webvr and aframe are cutting edge therefore should not take to easy keeping deps up to date. Quality of Aframe can suffer in long term. Can't say that this will happen, but risk factor it is for sure. For example it was known after three 79 came out that Aframe has issues with it, but so far nothing has been done to fix that while three is nr 1 dep. I don't know if that makes any sense to you and do you get what I'm worried about, but I shared my opinion anyway :). And I totally understand your point ex with polyfill, but can that be as excuse not to update nevre again or if then when everything craches?

**Comment by mkungla** [comment]
And if you have solid plan how to track that need of dep update, based on what to consider when to update - then please share. It would be useful info.

**Comment by dmarcos** [comment]
> As currently there are long time warnings for some deps. about to become deprecated. while now you already see warnings that your deps will stop working since their deps will not be included in future releases etc. 

@mkungla What warnings are you referring to?

**Comment by dmarcos** [comment]
> I find that this is a must that at the beginning of next version roadmap you update your deps and solve any exposed issues before you start building new futures on top of something which may not work anymore when you finally to the update.

Dependencies like `object-assign`,  `promise-polyfill` or `style-attr` play a very specific role and they fulfilled their role flawlessly. Why fixing what it's not broken and expose us to possible regressions or carrying additional features we don't need? A library increasing a version number does not mean that there are less bugs than the previous version or regressions have not been introduced.

**Comment by dmarcos** [comment]
Can we change this PR to just update `three.js` and evaluate each dependency individually. For the `devDependencies` I'm not that worried.

**Comment by mkungla** [comment]
i'm on gihub mobile at the moment and can't tell from head right now. Im back online within 3-4 h and can check then. But you can see by your self by installing aframe and (verbose) output of npm speaks for it self.

**Comment by mkungla** [comment]
i'm on gihub mobile at the moment and can't tell from head right now. Im back online within 3-4 h and can check then. But you can see by your self by installing aframe and (verbose) output of npm speaks for it self.

**Comment by mkungla** [comment]
Sure lets to three then.

**Comment by mkungla** [comment]
@dmarcos 
So I revert then all, but devDependencies?

> Can we change this PR to just update three.js

Sure, but which version? `0.77.1` which has been tested and working or `0.79` which breaks and requires to fix blocking issues with `textures`.

> and evaluate each dependency individually

That lives here for a while #1635

**Comment by dmarcos** [comment]
@mkungla can we move the devDependencies to a different PR?

**Comment by mkungla** [comment]
sure, what is going to be then with three?

**Comment by dmarcos** [comment]
@mkungla anything wrong with 0.80.0?

**Comment by mkungla** [comment]
Yes, as build finishes check the build logs. These failures are with three  >= 0.78

**Comment by mkungla** [comment]
@dmarcos I guess we have to start digging into these issues first and reference each issue to this PR?

**Comment by dmarcos** [comment]
@mkungla Yeah, it seems something is different with the `THREE.TextureLoader`. We have to investigate what has changed. Thanks for looking into this.

**Comment by ngokevin** [comment]
This has been done. Thanks though! We still need r82.

**Pull request closed without merging**
