### PR TITLE
Remove throttling of tracked-controls system tick. Chrome does not up…

### PR DESCRIPTION
**Pull request by dmarcos**
…date the gamepad poses unless we call getGamepads.

### CODE REVIEW

**Comment by machenmusik** [comment]
Why not #2978?

**Comment by machenmusik** [comment]
I think that part of the prior optimization is to avoid rebuilding controller list and emitting event when not needed.

**Comment by dmarcos** [comment]
I'm fine with https://github.com/aframevr/aframe/pull/2978 if it looks like this one 😄

**Comment by machenmusik** [comment]
ok - modified #2978, although it may later be worth a little thought on what the right check to avoid emitting `controllersupdated` would be, since handling that is pretty expensive

**Comment by dmarcos** [comment]
For the sake of simplicity I'm merging since it's what we need to fix the bug at hand.
We can do improvements on how we check the gamepads on https://github.com/aframevr/aframe/pull/2978

**Pull request merged**
