### PR TITLE
Document uppateSchema changes, add override

### PR DESCRIPTION
**Pull request by 3DataWill**
**Description:** Congratulations on the new release! This updates the docs for the optimized approach to `updateSchema` and the new `schemaChange` flag in component property definitions. Also, if you'll accept it, adds the `schemaAlwaysUpdates` component definition property to override the optimized behavior.

I've been using `updateSchema` to give some components entirely dynamic schemas that take new properties as they come in and give them a property type definition. I couldn't figure a way to do this with the `schemaChange` flag as the updates often contain only previously unknown properties.

**Changes proposed:**
- `schemaAlwaysUpdates` component definition property
- `updateSchema` is called on every update if `schemaAlwaysUpdates` is `true`

### CODE REVIEW

**Comment by ngokevin** [comment]
Would it be possible to pass the flag into every property?

**Comment by 3DataWill** [comment]
I read it as only checking for the flag on existing properties (new ones
don't have a schema definition yet until after updateSchema is called)

**Comment by ngokevin** [comment]
What do entirely dynamic schemas look like?

**Comment by 3DataWill** [comment]
I've included an example in the docs in this PR for how to setup an entirely dynamic schema. It allows me to have a single data management component that works with all different types of plot components that each have a different set capabilities and whose capabilities can be expanded by other components on the entity.

**Comment by 3DataWill** [comment]
I also looked at a less exposed option of a non-enumerable property property on the schema object to flag the need for continuous schema updates, but that would have required additional code changes in the component initialization path to pass the hidden property from the schema definition on to the instance schema object.

**Comment by ngokevin** [comment]
That's kinda funky. Can you just dynamically register components?

**Comment by ngokevin** [comment]
Closing for now. I think this case is too edge-y, feel free to post a code sample of your API though. I recommend breaking your component up if possible. Or finding a workaround (e.g., can you call something manually?).

**Pull request closed without merging**
