### PR TITLE
Add modelloaded event.

### PR DESCRIPTION
**Pull request by donmccurdy**
Helpful to know when model assets have finished loading.

For example, to get @ngokevin's shadow component working with .OBJ models:

```javascript

module.exports = {
  schema: {
    cast:     { default: false },
    receive:  { default: false }
  },

  init: function () {
    this.update();
    this.el.addEventListener('modelloaded', () => this.update());
  },

  update: function (previousData) {
    var data = this.data;
    // Applied recursively to support imported models.
    this.el.object3D.traverse(function(node) {
      if (node instanceof THREE.Mesh) {
        node.castShadow = data.cast;
        node.receiveShadow = data.receive;
      }
    });
  },

  tick: function () {}
}
```

### CODE REVIEW

**Comment by donmccurdy** [comment]
Oh, looks like there's a very similar change in #961 — no particular preference about the event name.

**Comment by ngokevin** [comment]
Yeah, might be organized to prepend the component name to the event.

I should probably make it past tense like yours though to be consistent with the rest of the codebase. Ideally, it would be present tense like how the rest of the web does it, but a bit too late now.

**Comment by donmccurdy** [comment]
(was originally requested by https://github.com/donmccurdy/aframe-obj-loader-component/pull/2)

'\*load' or '\*loaded' both seem fine.

As far as prepending "obj" and "collada", the only hassle would be needing to listen for unique events from each different model format. Could also do `emit('modelloaded', {format: 'obj', model: object})` though.

**Comment by ngokevin** [comment]
Hm, that works

**Comment by ngokevin** [comment]
Want to change this PR to handle for collada? I can handle for the OBJ since I have that already

**Comment by donmccurdy** [comment]
:+1:

**Comment by ngokevin** [comment]
lgtm

**Comment by dmarcos** [comment]
Thanks!

**Pull request merged**
