### PR TITLE
Information about bug for users using 0.6.0

### PR DESCRIPTION
**Pull request by rttomlinson**
Related to Issue #2961

**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by dmarcos** [comment]
I would not hardcode version numbers in the examples or reference specific bugs. The info will go quickly out of date and it will be hard to remember to update it

**Comment by rttomlinson** [comment]
What would you recommend doing? It was frustrating not understanding why the example was not working properly.

**Comment by dmarcos** [comment]
A bug in an example is the same as any other bug in the code base. The fix will ship in the next A-Frame version in a few weeks. You opened a good issue already to keep track of it. Any ideas on how we could fix it https://github.com/aframevr/aframe/issues/2961?

**Comment by rttomlinson** [comment]
Not yet. I will look into whether the issue is with the `event_set` component or if it is with something else within the code base first.

**Pull request closed without merging**
