### PR TITLE
Low Rate Video File to be uploaded to cdn

### PR DESCRIPTION
**Pull request by fuleinist**
**Description:**
For issue #1846 task 
**Changes proposed:**
Please download the video via https://drive.google.com/file/d/0B4IIadesQuavN0puUjNqLV84bG8/view?usp=sharing

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks, should we just use that video on desktop too?

**Comment by fuleinist** [comment]
Hi Kevin,

You can but the resolution is too low on big screen.... And this issue only
happen on iOS so far

Best Regards,

**Comment by ngokevin** [comment]
I see, thanks. I suppose the proper API might be something like:

```
<a-assets>
  <video id="city"></video>
  <video id="cityMobile></video>
</a-assets>

<a-videosphere degrading-src="desktopSrc: #city; mobileSrc: #cityMobile"></a-videosphere>
```

where degrading-src is a component...although it's a lot to bend backwards just for iOS. I wonder if we should just document the limitations and move on

**Comment by fuleinist** [comment]
I'd suggest to wait and see if mobile safari's html5 player will be upgraded to resolve this after iOS10's release

**Comment by ngokevin** [comment]
Thanks, will file an issue to have that example swap to mobile using a component and/or just wait for iOS 10.

**Comment by Utopiah** [comment]
Having encountered similar problems I usually serve 2 different video, 1 for desktop in high res and 1 for mobile (not just iOS) that is usually significantly lower.

**Pull request closed without merging**
