### PR TITLE
input-mapping system

### PR DESCRIPTION
**Pull request by fernandojsg**
Added input-mapping system: https://github.com/fernandojsg/aframe-input-mapping-component

### CODE REVIEW

**Comment by fernandojsg** [comment]
Not sure if it's the best idea to start the PR until we'll solve the issues we're discussing in my repo and then push all the changes, or merge it and evolve it here, moving the discussion to this repo too.
/cc @ngokevin @dmarcos thoughts?

**Comment by dmarcos** [comment]
@fernandojsg I think we can deal with the issues in further iterations of the mapping. The current design is useful and easy to understand / use. I commented on https://github.com/fernandojsg/aframe-input-mapping-component/issues/3 that it is the only one that could change the current design, the others are refinements. We had discussed that problem before and settled on organizing the mappings per controller instead of per action for the reasons described in the issue: Organizing mappings per controller is closer to how users and developers reason about mappings. I grab a controller and I imagine how the interaction will feel and how the different actions map to the buttons.

**Comment by cvan** [comment]
@trevorfsmith: since you’ve been assessing and preparing for tackling universal XR/MR input fragmentation, I wanted to get your insight on this - if you haven’t already take a look. thanks for taking a look :smile:

**Comment by TrevorFSmith** [comment]
This looks like a good start and addresses a lot of the issues with mapping lots of input types to higher level semantic events.

A few notes:

When I wrote a similar input manager for Spaciblō (classes here: https://github.com/Spaciblo/spaciblo-core/blob/master/docroot/js/spaciblo-input.js and default schema here: https://github.com/Spaciblo/spaciblo-core/blob/master/docroot/js/spaciblo-default-input-schema.js) it became quickly apparent when making apps that I needed  to know how the higher level event was triggered. So, the app might treat differently events from left- or right-handed controller or from gaze control.

One of my working theories is that a MR app framework needs to keep track of global app state (type of pose data, type of display, type of controllers, etc) so that the input mapping can be entirely swapped out. For example, if a handset is in flat page mode then it needs a different input map handling touch inputs than it would in magic window pass-through AR mode which is also different from when in a HMD doing VR.  So, the same lower level inputs lead to different higher level events, depending on MR mode.

Diego, I suspect that this is related to the conversation that you're having with @blairmacintyre about the use of "presenting" to indicate global app state. It seems like we need state with more info, like a data structure that represents the current display, the UI mode (flat, overlay, in-scene), the reality (pass-through AR, see-through AR, VR), and the input schema.

**Comment by fernandojsg** [comment]
I believe we could still handle these global states as presenting or not with the states implemented currently and the app could swap between these mapping states as the app change itself to another state.

**Comment by ngokevin** [comment]
Maybe we should let the component/system API bake before we place in the core. We've been quick to put components into core before (object `pool`) that haven't gotten a lot of run. I'll use it in one of my projects and can provide feedback/PRs.

**Comment by fernandojsg** [comment]
@ngokevin yep I agree with you. I'll keep improving it on my repo and testing it with the rest of the demos and once it get mature we could decide how to include it here

**Comment by dmarcos** [comment]
The `input-mapping` component is still under heavy development. It is a bit premature to pull into core. I'm closing this for now and we will reconsider for `0.9.0`. Better let it mature as a 3rd party component for now.

**Pull request closed without merging**
