### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by rajeshwariramya**
I removed the meta refresh tag, as it's not necessary for a basic HTML template. If you want to add any content to the body

**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by dmarcos** [comment]
@vincentfretin Do we still need the index file with webpack?

**Comment by vincentfretin** [comment]
Indeed this file is not used anymore, it was only for budo to do the redirect to examples it seems. With webpack it serves examples directly as the root.
You can remove the file.

**Comment by dmarcos** [comment]
@rajeshwariramya you want to remove the file? thanks

**Comment by dmarcos** [comment]
I removed the file. Thanks

**Pull request closed without merging**
