### PR TITLE
Fix increasing offset when entering VR for non positional devices

### PR DESCRIPTION
**Pull request by vincentfretin**
This fixes issue #3051

### CODE REVIEW

**Comment by vincentfretin** [comment]
If `el.getAttribute('camera').userHeight` returned 0, `getUserHeight()` always returned DEFAULT_CAMERA_HEIGHT instead of 0.

` <a-entity camera look-controls />` now renders again userHeight to 0 like it's supposed to.

**Comment by vincentfretin** [comment]
But maybe this fix introduces a regression for #3000, @olga-microsoft can you please verify?

**Comment by ngokevin** [comment]
thanks!

**Comment by vincentfretin** [comment]
Ah, I just looked at it again. It doesn't fix the issue with `<a-camera />` which set camera.userHeight to 1.6 by default". I still have an increasing offset. This fixes only the case where you really want a camera on the floor.

**Pull request merged**
