### PR TITLE
Adding x-axis to look controls #4957

### PR DESCRIPTION
**Pull request by a0m0rajab**
Related issue: #4957

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Calculating deltaX

**Review by marcbuils — COMMENTED** [review]
Thanks for this update, I hope it will be merged ;)

**Comment by a0m0rajab** [comment]
@marcbuils You can check the issue, the maintainer mentioned it's a design decision .

**Comment by dmarcos** [comment]
Closing this. As mention de lack of x-axis is a deliberate decision. Thanks

**Comment by a0m0rajab** [comment]
Related discussion where the decision was made: https://github.com/aframevr/aframe/issues/4190

**Pull request closed without merging**
