### PR TITLE
change the git clone URL

### PR DESCRIPTION
**Pull request by salmanfarisvp**
**Description:**
the git clone url `git clone git@github.com:aframevr/aframe.git` have an issue []( https://github.com/aframevr/aframe/issues/2178l) also `git clone https://github.com/aframevr/aframe.git` this one working fine

change " git clone git@github.com:aframevr/aframe.git" to "git clone https://github.com/aframevr/aframe.git"

### CODE REVIEW

**Comment by dmarcos** [comment]
@salmanfarisvp what issue are you having with `git clone git@github.com:aframevr/aframe.git`

**Comment by dmarcos** [comment]
I see. This seems to be the issue 
https://github.com/aframevr/aframe/issues/2178#issuecomment-267395742

**Comment by salmanfarisvp** [comment]
@dmarcos  Permission denied (publickey). fatal: Could not read from remote repository. while am trying to Local Installation and Development via
git clone git@github.com:aframevr/aframe.git
but stuck here
Cloning into 'aframe'...
Permission denied (publickey).
fatal: Could not read from remote repository.
``
[](https://github.com/aframevr/aframe/issues/2178)

**Comment by dmarcos** [comment]
I personally prefer to use `git@github.com:aframevr/aframe.git` since it uses the keys already setup in my system. @ngokevin What do you think?

**Comment by salmanfarisvp** [comment]
@dmarcos i think` git clone https://github.com/aframevr/aframe.git` this one is more simple to use . if someone did't setup the key and he will stuck there ,especially newbies like me

**Comment by dmarcos** [comment]
Thanks!

**Pull request merged**
