### PR TITLE
Fix cursor example

### PR DESCRIPTION
**Pull request by amberroy**
- Fix query selector to match all cubes, by using wildcard (*)
- Also upgrade to using a-camera and a-cursor tags, instead of depreciated attributes

### CODE REVIEW

**Comment by ngokevin** [comment]
Probably keep using a-entity. Those aren't deprecated. a-camera and a-cursor are helpers and we'd rather have these examples not be testing that layer

**Comment by ngokevin** [comment]
Thanks!

**Comment by dmarcos** [comment]
a-camera and a-cursor are just aliases of a-entities + components. These test examples illustrate how to configure a camera and a cursor using components. If we use primitives / aliases we lose the learning value.

**Comment by amberroy** [comment]
Understood. I reverted back to a-entity, now it's just a one-liner fixing the query selector (which wasn't matching anything before).

**Comment by dmarcos** [comment]
@amberroy nice! thanks! can you squash your commits?

**Comment by amberroy** [comment]
squashed.

**Pull request merged**
