### PR TITLE
bump rStats (fixes #1124, fixes #876, fixes #877)

### LINKED ISSUE #876: rStats tries to load rStats.css (when we don't need it to)
it looks like it's trying to load [http://localhost:9000/examples/style/rStats.css](http://localhost:9000/examples/style/rStats.css) when it should be [http://localhost:9000/style/rStats.css](http://localhost:9000/style/rStats.css).

Cause: https://github.com/aframevr/aframe/blob/253c56c/src/core/a-scene.js#L623

I thought we fixed this by bundling `rStats.css` in `src/index.js`? @ngokevin?

### LINKED ISSUE #877: Do not load 'Roboto Condensed' web font for rStats
It'd be nice if rStats didn't load the [Roboto Condensed](https://github.com/aframevr/aframe/blob/dev/vendor/rStats.js#L44-L45) web font. I wish we could monkeypatch it so we don't have to change the `rStats.js` file.

Also, it should be using `https` Google Fonts URI.

### LINKED ISSUE #1124: Bump rStats
I made a few PRs there

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by ngokevin** [comment]
I don't see the stats.

**Comment by cvan** [comment]
> I don't see the stats.

they there.

and updated styles to be consistent w/ previous ones.

**Comment by ngokevin** [comment]
Can we make it a bit closer? More compact, less bold, more aligned. You're pretty busy so might want to wait until later to fiddle with this since it's pretty minor.

screen shot 2016-03-10 at 5 27 39 pm

screen shot 2016-03-10 at 5 27 57 pm

**Comment by cvan** [comment]
> Can we make it a bit closer? More compact, less bold, more aligned. You're pretty busy so might want to wait until later to fiddle with this since it's pretty minor.

lol I'm impressed

**Comment by cvan** [comment]
tightened things up:

screenshot 2016-03-22 13 18 55
screenshot 2016-03-22 13 18 44

I mainly want to get this in so there's not a 404 network request on every A-Frame page load.

**Comment by cvan** [comment]
tightened things up:

screenshot 2016-03-22 13 23 36
screenshot 2016-03-22 13 23 26

I mainly want to get this in so there's not a 404 network request on every A-Frame page load when stats are enabled.

**Pull request merged**
