### PR TITLE
Update a-videosphere.md

### PR DESCRIPTION
**Pull request by wrjanan**
**Description:**
simple methods to implement on videosphere

**Changes proposed:**
- how to set current time of video in videosphere
- how to play video

### CODE REVIEW

**Comment by wrjanan** [comment]
can update more methods should this be useful

**Comment by ngokevin** [comment]
This is covered at https://aframe.io/docs/0.8.0/components/material.html#video-textures, I would add a link to there.

**Comment by ngokevin** [comment]
Hey @wrjanan, can you update the PR to just add a link to above? `../components/material.html#video-textures`? Thanks!

**Comment by wrjanan** [comment]
Updated the PR to add the link, am uncertain if the link is to the right location.

Is it a common issue in github where we are unable to test the linking accuracy since the preview of links are stored in a hosting URL?

Thank you @ngokevin for the learning experience !

**Comment by ngokevin** [comment]
If you view it in GitHub, or npm run docs, you can test the link. It looks good!

**Pull request merged**
