### PR TITLE
Moves variable from closures to the component instance so multiple lo…

### PR DESCRIPTION
**Pull request by dmarcos**
…ok-controls don't collide

**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by ngokevin** [comment]
Tested r+

Would later like https://github.com/aframevr/aframe/pull/1853, but will need to rebase after this.

**Comment by ngokevin** [comment]
Is this an issue with other components that utilize closures?

**Comment by dmarcos** [comment]
yes, if people are going to use multiple instances. I found this bug with the motion controls work. I had to cameras with look-controls and weird things started to happen because they were stepping on each others toes

**Comment by dmarcos** [comment]
We merge this and we can look at other controls

**Comment by ngokevin** [comment]
So tracked-controls could have been buggy due to this?

**Pull request merged**
