### PR TITLE
[docs] Update <a-curvedimage> Fine tuning

### PR DESCRIPTION
**Pull request by fcor**
**Description:**
Update <a-curvedimage> Fine tuning description.

**Changes proposed:**
- Added a brief description on how to determine the properties to render the image correctly.

### CODE REVIEW

**Comment by ngokevin** [comment]
Can you drag the image into a GitHub comment text box to get a GitHub-hosted image? The Uploadcare stuff could expire.

**Comment by fcor** [comment]
Sure.
firefox_2018-10-06_21-27-18

**Comment by fcor** [comment]
How can I resize the image this way?

**Comment by ngokevin** [comment]
Don't need to, the dosc have CSS

**Comment by ngokevin** [comment]
thx

**Pull request merged**
