### PR TITLE
Make sure that init/update are not called when invoking flushToDOM on a non loaded entity

### PR DESCRIPTION
**Pull request by dmarcos**
Fixes inspector https://github.com/aframevr/aframe-inspector/issues/409

### CODE REVIEW

**Comment by ngokevin** [comment]
Can you explain the remove of the `updateAttrForCache` line?

**Comment by dmarcos** [comment]
It's not removed. It's now part of `updateProperties`. It was redundant before in the constructor since it is also done in `updateProperties` as well

**Comment by ngokevin** [comment]
I'm confused that we're now passing `attr` (presumably the attribute name) into `updateProperties` now when before we were passing an `attrValue`, and the function seems to expect an `attrValue`.

**Comment by dmarcos** [comment]
`this.attrValue` is updated by `updateAttrForCache`. Now everything happens inside `updateProperties`

**Comment by ngokevin** [comment]
OK. It seems like something needs to change then, either the function signature or what we pass into updateProperties:

```js
var Component = module.exports.Component = function (el, attr, id) {
  // ...
  this.updateProperties(attr);  // THIS IS THE ATTRIBUTE NAME.
  // ...
};

Component.prototype = {
  // ...
  /**
   * @param {string} value - HTML attribute value.
   */
  updateProperties: function (value) {
    // ...
    // BUT THIS FUNCTION EXPECTS AN ATTRIBUTE VALUE.
  }
}
```

**Comment by dmarcos** [comment]
The jsdoc for the component constructor was wrong. attr was actually the value of the attribute and not the name. I fixed it.

**Comment by ngokevin** [comment]
r+

**Pull request merged**
