### PR TITLE
Bump THREE to r87

### PR DESCRIPTION
**Pull request by dmarcos**

### CODE REVIEW

**Comment by dmarcos** [comment]
@donmccurdy Bumping THREE to r87. It seems that `GLTF2Loader` has been renamed to `GLTFLoader`

**Comment by donmccurdy** [comment]
Does r87 force us to change any other VREffect usage?

**Comment by dmarcos** [comment]
I don't believe show. I will do a sanity check in VR to make sure it works.

**Comment by dmarcos** [comment]
Tried on Gear VR and everything seems to work.

**Pull request merged**
