### PR TITLE
Make sure that when an empty string  is passed to the `src` property …

### LINKED ISSUE #2388: Removing or setting a null for SRC in a material doesn't works
**Description:** 
If we've an entity with a material set and a `src` loaded, if we try to clear the `src` value by removing the `src`attribute itself or by setting it to null or "", it will clear the value but it will still keep the texture binded to the entity

- A-Frame Version: v0.5.0
- Platform / Device: 
- Reproducible Code Snippet or URL: http://codepen.io/fernandojsg/pen/NdooBz

### PR DESCRIPTION
**Pull request by dmarcos**
…of the material the texture is removed (fix #2388)

### CODE REVIEW

**Comment by dmarcos** [comment]
@machenmusik @ngokevin alternative to https://github.com/aframevr/aframe/pull/2393

**Comment by machenmusik** [comment]
the reason to have the check inside setMap is to handle the case where the property has changed in between the original call and the texture load that results in setMap (i.e. if you asked a texture to be loaded then changed it before the load completes, don't apply the texture in setMap)

removing it will cause a regression and hard to trace errors...

**Comment by dmarcos** [comment]
@machenmusik what about now? A bit more clear?

**Comment by machenmusik** [comment]
it seems that the check to avoid redundant texture load operations wouldn't work then, also not sure it would work correctly for cases whether multiple textures being loaded for same material/shader.

what in #2393 annoys you?

**Comment by dmarcos** [comment]
This code is overly complicated and difficult to understand and maintain. I'm looking for opportunities to improve it.

**Comment by machenmusik** [comment]
@dmarcos take a look at latest #2393 ?  should be much more comprehensible

**Pull request closed without merging**
