### PR TITLE
adding an example for interaction page

### PR DESCRIPTION
**Pull request by PAPERPANKS**
**Changes proposed:**
- adding a new example to illustrate interaction in A-Frame

### CODE REVIEW

**Comment by PAPERPANKS** [comment]
This is in response to the pull request #3068

**Comment by ngokevin** [comment]
Thanks! Can you update to 0.7.0, change the text to say hover vs. click, and apply a gray default color?

**Comment by PAPERPANKS** [comment]
@ngokevin i have changed the code that you have asked

- `<script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>`
- `<a-text value="... by hovering on  ... ></a-text>`
- default color - `#E0E0E0`

**Comment by PAPERPANKS** [comment]
@ngokevin  well if you are satisfied with the result can you remove the **need changes** tag

**Comment by ngokevin** [comment]
It's already merged so it's fine. Thanks!

**Pull request merged**
