### PR TITLE
fixed: components+systems would misbehave with multiple scenes

### PR DESCRIPTION
**Pull request by ProPuke**
**Description:**

Currently, one of the barriers to supporting multiple scenes (see #916) on the same page is that components and systems do not interact correctly when multiple scenes exist.

Each scene contains its own systems, but the last scene to initialise always overwrites the global `Component.__proto__.system` property of its components. This means that systems and components for earlier scenes no longer function correctly (for instance lights don't attach themselves to their correct lights system, meaning default lighting isn't disabled).

This fixes that by initialising components _after_ they have been attached to the scene, and setting their `Component.system` instance property to the correct scene system. Any attempts to update component properties before this happens are queued and then processed after attachment and initialisation; However DOM updates still occur as expected, to ensure DOM manipulation and debug serialisation still all work as expected.

**Changes proposed:**
- `Component.__proto__.system` is now longer set by systems upon system initialisation
- Component initialisation now occurs as a result of the `load()` callback and `updateComponents()` once the entity has been attached to a scene
- Component initialisation sets its local `system` by accessing its local `el.sceneEl.systems`. This occurs immediately within the `Component` base ctor, before local construction and `init` occurs.
- Attempts to update the properties of components before initialisation occurs succeed successfully and update the DOM where expected. The actual component update, however, is queued and only executed once `updateComponents()` has been called on the attached parent entity.

### CODE REVIEW

**Comment by ProPuke** [comment]
I also started clearing sceneEl on entity detach, but this was breaking unit tests, so I undid that.

This feels like a dependency on broken behaviour?

The docs simply say "An entity has a reference to its scene element.". Which would indicate to me it would be null if an entity was no longer attached a scene.

But if it's cleared on detach things break, so I let it linger to whatever it used to be :S

**Comment by ProPuke** [comment]
Okay, there's also a few tests that intentionally try and access the raw component objects of entities before they're attached to a scene, or attach entities to a `<body>` instead of an `<a-scene>`. These fail :S

I'd be in favour of adding a caveat rule to the first (that the entity must be in a scene before the component objects can be accessed), in order to support multiple scenes, and changing the latter as it feels like incorrect/undefined behaviour.

**Comment by dmarcos** [comment]
We recommend replacing the content of a single scene instead of having multiple in the same page if you want to swap content. Do you want to render multiple scenes simultaneously? It’s already problematic to get good performance on a single scene. These are also API breaking changes for components that access systems. In general tests should not be skipped to accomodate new functionality. Either the tests have to change if they don’t check the right things anymore or the PR has to be modified to not break pre existing functionality.

**Comment by ngokevin** [comment]
While this fix may improve things for multiple scenes, I think we shouldn't go down that route for now as it will make things more complex. For support of multiple scenes, more things have to happen (e.g., three.js does not even support multiple scenes with WebGL renderer). See that #916 is closed.

**Pull request closed without merging**
