### PR TITLE
Remove 'collada-model' component.

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes https://github.com/aframevr/aframe/issues/3793.

There are a few issues with this PR that should be discussed or resolved before merging.

- [x] ~~Some scenes still require manual adjustment to colors, where glTF models are present alongside `material` colors and textures. Automatic adjustments are possible (https://github.com/aframevr/aframe/pull/3757) but may require some time to get right.~~
- [x] ~~Issues with conversion of the `tree1.glb` and `tree2.glb` models; the "shadow" masks aren't quite right.~~

### CODE REVIEW

**Comment by ngokevin** [comment]
I'm okay if the model examples aren't perfect color-wise, at least for this PR.

**Comment by dmarcos** [comment]
Thanks @donmccurdy for staying on top. I'm good with deprecating now. This way it won't come as a surprise in 1.0.0.

**Comment by dmarcos** [comment]
Thanks!

**Comment by olivierFalloff** [comment]
Hello
I have been using a-frame since 2018 to show my scenographies to the directors I work for. (https://scenographie-vr.com) (besides I still do not know how to thank you
of your fantastic work !!) I used the colladas files for my objects and everything was working great and my textures were
as I wanted. But since the webxr appeared it is no longer possible to use
collada I have tried the Gltf files but it is too heavy and not satisfactory. So I wanted to know how to put collada back into the a-frame scipts. I tried: "collada-model-legacy.js"
with "ColladaLoader.js" in another folder but it doesn't work. Do you have a solution?
Thank you

**Comment by olivierFalloff** [comment]
Hello
It's a shame that Collada-models don't exist anymore in a-frame, it's not possible to keep a component?

**Pull request merged**
