### PR TITLE
[docs] Update cursor page with mouse click example.

### PR DESCRIPTION
**Pull request by madebynoam**
Added a Glitch example to the docs, to demonstrate how to allow mouse clicks on entities with A-Frame.

### CODE REVIEW

**Comment by dmarcos** [comment]
Cool thanks! Can you add a hover effect on the elements to emphasize you can interact with them using the mouse?

**Comment by madebynoam** [comment]
Sounds good. Just updated the Glitch project with basic hover effects for interaction feedback.
Decided to use the event-set component for those feedback interactions, since it's simpler to demonstrate than writing custom components in this context. But let me know if you think it should use a custom component with addEventListerer.

**Comment by dmarcos** [comment]
Thanks! Congrats for your first PR

**Comment by madebynoam** [comment]
Awesome, thanks!

**Pull request merged**
