### PR TITLE
Update webvr-polyfill dependency. the fork is now hosted on the aframevr org (fix #2495)

### LINKED ISSUE #2495: Update Polyfill to 0.9.26
A new version has been released with some bugfixes for recent versions of chrome on android.

### PR DESCRIPTION
**Pull request by dmarcos**
I moved the webvr-polyfill fork to the aframevr org and rebase on top of the later master

### CODE REVIEW

**Comment by dmarcos** [comment]
@HalfdanJ  Can you verify that this fix your problem?

**Comment by machenmusik** [comment]
we're going to want this for aframevr/webvr-polyfill#6 at least...

**Comment by jsantell** [comment]
Related: #2700

**Comment by ngokevin** [comment]
#2700

**Pull request closed without merging**
