### PR TITLE
Make vrdisplayactivate driven enter-vr path more robust

### PR DESCRIPTION
**Pull request by dmarcos**

### CODE REVIEW

**Comment by dmarcos** [comment]
This is ready.

**Comment by gfodor** [comment]
qq on this -- is this patch dependent upon anything specific in `super-three`? we're looking to cherry pick this commit into our A-Frame fork which adds (hacky, not ready for PR) multiview support, but are hesitant to move over to `super-three` without more testing/validation. Thanks!

**Comment by dmarcos** [comment]
@gfodor super-three is stock THREE + PR waiting to merge upstream. At the moment https://github.com/mrdoob/three.js/pull/16015, https://github.com/mrdoob/three.js/pull/15347 and https://github.com/mrdoob/three.js/pull/15290 

Intent is always using stock THREE. If you can spare a comment on those PRs might help expedite merge and put us back on track.

**Comment by gfodor** [comment]
Cool. I upvoted the resolution one, which I've seen -- we haven't tried
WebXR support yet so can't confirm the others but looks like others have.

**Pull request merged**
