### PR TITLE
allow vertical touch-movement if you are not in vr-mode

### PR DESCRIPTION
**Pull request by goltra**
**Description:**
Added ability to move vertically touching screen in not vr-mode

https://github.com/aframevr/aframe/issues/2306

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks! Not allowing vertical touch is a deliberate decision because it becomes very confusing for de user in combination with device motion. You quickly lose the reference of where is up/down and you can only recover by reloading the page

**Comment by morandd** [comment]
I just bumped up against this issue as well, and I see it has been raised several times in the github discussion.

It's a bit confusing for us A-Frame users because the "look-controls" component covers 3 quite different interaction styles: desktop with a mouse, mobile with multitouch, and VR/magic window mode. 

Why not allow pitch, within definable min and max angles, in touchmove in look-controls? This makes sense for my use case, and from the previous queries about this, it seems I'm not alone. Alternatively, another way to do this could be to add a toggle to look-controls so that ptich/yaw are controlled by single touch in 2d mode, and by deviceorientation in vr mode.

Overall, it would be really nice if it were easier to switch between camera control schemes between default, touchscreen device, and VR/magic window. For example on the deskop or mobile device, maybe you start with orbit controls, but then when you enter VR with a headset/cardboard/"magic window" mode, you switch to free-look controls.  Currently we users have to write our own components to juggle cameras, but I think having some defaults baked into AFrame would be quite helpful. Over in the orbit-controls I submitted a PR with to add a "vrCamera" attribute, which lets the user specify a different camera element ID that gets activated on enter-vr, then switch back to orbit on exit-vr. Until (...) this is accepted I have written my own component to do this juggle.

Ok, sorry for a bit of a soliloquy/jeremiad. AFrame is awesome! Just trying to offer some constructive contributions -- and I'm happy to make some PRs to manifest this if that's helpful.

**Comment by ngokevin** [comment]
It's difficult to support every single use case. We prefer that the standard implementation remain focused on a default preset. This is better as increased complexity in code will increase maintenance in the long run and slow releases. Components can be built or customized that can be updated or published asynchronously from A-Frame. I think an okay compromise that at least it's possible to achieve what you need via components.

**Comment by morandd** [comment]
Yep, understood about wanting to keep it simple. However I would say the current state of affairs having to juggle cameras is not so user friendly. 

My situation is I think a pretty common one:
I want to show off a 3d object on a web site. It should work on the desktop, on a phone/tablet, and with a VR headsset or cardboard. Some scenes I want to show using orbit controls, and some scenes I want to use a free look camera.

I thought this would work out of the box so to say.

Here is the logic to switch cameras to accomplish this:

```
Scenes using the orbit-controls paradigm
	On Desktop:
		start: use orbit controls
		enter-vr: save orbit cam position. Switch active cam to look-controls. 
		exit-vr: save look-control position. Restore orbit-cam position. Switch active to orbit cam
	On mobile:
		start: use orbit-controls
		enter-vr: save orbit cam position. Switch active cam to look-controls. 
		exit-vr: save look-control position. Restore orbit-cam position. Switch active to orbit cam

Scenes using the look-controls paradigm
	On Desktop:
		start: use look-controls
		enter-vr: Remain in look-controls mode
		exit-vr: Reset camera pitch to 0'. Remain in look-controls mode
	On mobile:
		start: use multitouch-look-controls*
		enter-vr: switch to regular look-controls
		exit-vr: switch to multitouch-look-controls

*multitouch-look-controls adds two gestures: single finger up/down drag to pitch, and pinch to zoom/dolly.
```

If I were to share my "controller controller" code for the above,  any suggestions where best I should contribute it? For new users (like me) there are already plenty of camera controller components floating about, so it would be nice to contribute this code / readme / blog entry to an established codebase.

**Comment by ngokevin** [comment]
I understand there are many use cases, but we try to set the direction of the project towards true WebVR. You can add it to https://github.com/aframevr/awesome-aframe, publish it and we'll feature it on the blog, or contribute a FAQ entry on how to customize controls. Thanks!

**Comment by dmarcos** [comment]
The decision to lock finger panning to the `x` axis is what we observed delivers the best experience for the majority of applications when combined with gyro orientation that all tablets and phones have. If you allow for vertical panning the user quickly loses the notion of up / down and it gets disorienting. The good thing about a-frame is that it's very easy to override the defaults if your application does not fit within those design decisions. We cannot cover every single use case on A-Frame core because as @ngokevin said we would not be able to guarantee good quality for all the possible combinations of controls moving forward. We want aframe core to be useful with sane defaults but still contain the complexity of the code base. We've been focusing the efforts on making very easy for anyone to modify and extend the default behavior.

**Pull request closed without merging**
