### PR TITLE
add sRGB encoding to perspective screenshot

### PR DESCRIPTION
**Pull request by kfarr**
**Description:** add sRGB encoding to perspective screenshot, fixing #4817

### CODE REVIEW

**Comment by dmarcos** [comment]
I fixed the broken tests on master. If you rebase this is ready to merge. Thanks so much for the patience.

**Comment by kfarr** [comment]
rebased and no worries, I'm always learning new things working with you and the community!

**Comment by dmarcos** [comment]
Thank you!

**Comment by diarmidmackenzie** [comment]
As per a thread in the slack community, I'm concerned that this fix has had a bad effect on colors in some screenshots.

This is what a screenshot of teh HelloWebVR page looked like in 1.2.0.
screenshot--1645741701810

This is what it looks like in 1.3.0.
screenshot--1645741354272

This glitch shows that if you revert the changes made in this PR, you get back to the previous coloring (i.e. this change is the cause of the difference).
https://glitch.com/edit/#!/sly-sixth-topaz?path=index.html%3A19%3A9

I'll raise a separate issue to track this, but thought it made sense to flag here as well.

**Comment by kfarr** [comment]
Thanks, replied here: https://github.com/aframevr/aframe/issues/5014

**Pull request merged**
