### PR TITLE
Fixed yOffset not being used to change y position of text

### PR DESCRIPTION
**Pull request by Pluto8195**
addresses issue mentioned in  #3762

simply included (+ data.yOffset) to mesh position of text
`mesh.position.y = y * textScale + data.yOffset;`

### CODE REVIEW

**Comment by ngokevin** [comment]
Hm, seems it's used at https://github.com/aframevr/aframe/blob/ea2142b4b487bf41e435b28ea2d089739a6dd31c/src/components/text.js#L391 in a different way.

**Comment by Pluto8195** [comment]
@ngokevin can you explain what the yOffset value is suppose to effect?

**Comment by ngokevin** [comment]
Supposed to effect per-char offset but this solution might be able to replace it. I have to dig down to why the original offset logic was meant for.

**Comment by Pluto8195** [comment]
comment above schema
`// `yOffset` to adjust generated fonts from tools that may have incorrect metrics.`

but I find that being able to just manipulate the y makes formatting text generally much easier

**Comment by ngokevin** [comment]
Thanks for waiting.

Can you figure out what effect it has on these lines? https://github.com/aframevr/aframe/blob/ea2142b4b487bf41e435b28ea2d089739a6dd31c/src/components/text.js#L401 ... Does the yOffset stack? Is the Roboto font hack necessary any more?

**Comment by dmarcos** [comment]
Closing due to inactivity. can reopen if necessary. Thanks

**Pull request closed without merging**
