### PR TITLE
remove event.preventDefault in look-controls canvas mousedown (fixes #1729)

### LINKED ISSUE #1729: WASD control behaves oddly on Codepen with master
**Description:** 

With 0.2.0 I can click on the window and walk around with the WASD keys. But with master, control stays with the editor often resulting in WASD characters being added to code accidentally. Autorun makes this extra frustrating.

Master: http://codepen.io/bryik/pen/dXgQdQ

0.2.0: http://codepen.io/bryik/pen/yJRQKr

- A-Frame Version: master
- Platform/Device: Desktop Chrome/Codepen

### PR DESCRIPTION
**Pull request by ngokevin**
**Description:**

https://codepen.io/ngokevin/pen/AXNZwV

Allow CodePen to listen to click of the scene to blur their text editor.

### CODE REVIEW

**Comment by bryik** [comment]
This does fix the issue, but the grabbing cursor is gone.

**Comment by ngokevin** [comment]
Oops, I updated the CodePen. Didn't have look-controls attached...

**Comment by bryik** [comment]
All good with the CodePen now.

**Comment by mkungla** [comment]
Yes that seemed to solve it

**Pull request merged**
