### PR TITLE
Adding example to interaction page

### PR DESCRIPTION
**Pull request by PAPERPANKS**
**Changes proposed:**
- adding an example related to events and interaction in A-frame
- editing `readme.md file` , adding `target="_blank" ` to `<a>` tags

This commit is ready for review.

### CODE REVIEW

**Comment by ngokevin** [comment]
This is cool, but swapping the environment causes hangs in the scene, right?

**Comment by PAPERPANKS** [comment]
@ngokevin may be there are some back-end issue but this may be a best example to add and showcase.

**Comment by ngokevin** [comment]
I mean the performance is not really good, we can't really recommend slow scenes.

**Comment by ngokevin** [comment]
Perhaps do something less intensive on the clicks. For example, changing some text, or making something a different color, popping up elements

**Pull request closed without merging**
