### PR TITLE
AFRAME.registerComponent("name",...

### PR DESCRIPTION
**Pull request by polygontwist**
// <a-entity "name"></a-entity> 
that should be the same

**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by donmccurdy** [comment]
I think this example should remain "pointlight", registering "light" will throw an error as it's already defined. The intention here is to show how a user could create a new component for their particular needs. Maybe `area-light`, using `new THREE.RectAreaLight( 0xffffff, undefined,  2, 10 );`, would be a better example since that's not already provided by A-Frame?

**Comment by dmarcos** [comment]
@donmccurdy is correct. Thanks for submitting

**Comment by polygontwist** [comment]
in the following "Removing an Object3D From an Entity" is the same error

**Comment by dmarcos** [comment]
@polygontwist You might have got confused with object3D named `light` which is different than the component name. The example illustrate how to add / remove object3Ds on a custom component and it is named `pointLight` so it does not collide with the built in `light` component in A-Frame.

**Pull request closed without merging**
