### PR TITLE
Example Added

### PR DESCRIPTION
**Pull request by aayushigupt**
**Description:**

**Changes proposed:**
-
-
-

### CODE REVIEW

**Comment by dmarcos** [comment]
Is this PR intentional?

**Comment by dmarcos** [comment]
Closing since it looks accidental. We can reopen if necessary.

**Comment by aayushigupt** [comment]
Hey
I have added example which was made by me.
It is not accidental

**Comment by dmarcos** [comment]
Is your intent to merge this PR in A-Frame central repository? What is your example trying to illustrate?

**Comment by aayushigupt** [comment]
Hello
Basically it consists of a room where there are number of boxes lying and
after that we can put many things on it. Its like showcasing.

**Comment by aayushigupt** [comment]
I'll make more changes in it afterwards when ill learn more about aframes

**Comment by dmarcos** [comment]
Thanks for submitting the PR and sorry for the confusion. Each of the [A-Frame examples](https://aframe.io/aframe/examples/) is meant to illustrate a specific feature for reference and learning purposes. You're more than welcome to share your work with the community on [Slack or Discord](https://aframe.io/community/). Looking forward to seeing what you make and glad to have you on board.

**Comment by aayushigupt** [comment]
Yes Sure, and I'll try to add new features of aframe in that example.
Thanks

**Pull request closed without merging**
