### PR TITLE
Modified camera userHeight under examples.

### PR DESCRIPTION
**Pull request by mkungla**
After update default camera.userHeight and user-height some
examples needed logical adjustment to reflect that. And when you
are creating cameras with specific position you better use camera
component instead a-camera since it would make more sense there.
So to avoid that you'll have to position your camera
(prefered positon - camera.userHeight)

### CODE REVIEW

**Comment by ngokevin** [comment]
I think rather than switching to use `<a-entity camera>`, we should set `user-height="0"` for some of these examples since they have no concept of standing.

**Comment by mkungla** [comment]
that makes sense, will change to `<a-camera user-height...`

**Comment by mkungla** [comment]
#1737 has to be fixed before I can confirm that changes have correct effect.

**Comment by mkungla** [comment]
I checked all the examples

**Comment by ngokevin** [comment]
Thanks!

**Pull request merged**
