### PR TITLE
Added ring template (Fixes issue #157)

### PR DESCRIPTION
**Pull request by cemkod**

### CODE REVIEW

**Comment by cvan** [comment]
first off, woo thanks!

we haven't mentioned it in the Contributing doc yet (#241), but no need to run `dist` when pushing changes. also, see #320 that uses the `build/` when serving the local server (instead of `dist/`).

also, looks like `a-ring.html` is missing in this branch

**Comment by cemkod** [comment]
I seem to have forgot to add the files. I'm still learning git. Sorry for that.

So is doing **npm start** after changing the files enough to test the changes I made?

**Comment by cvan** [comment]
> So is doing npm start after changing the files enough to test the changes I made?

until #320 lands, the best way to test is to

1. run `npm start`
2. change `../../dist/aframe.js` to `../../build/aframe.js` in `examples/template-ring/index.html`
3. make changes, load the page, etc.

it'd probably be easier to do a new branch to remove the `dist/` changes. also, something we (I) haven't done a good job of communicating yet (again: apologies, will address in #241) is that PRs should be made against `dev` (unstable, under "development") instead of `master` (stable).

so you'll likely want to close this PR, commit only `examples/` and `elements/` files, and open a new one PR against `dev` instead of `master`.

thanks for your understanding - and thanks for contributing!

**Comment by cemkod** [comment]
I'm afk now. No worries, I understand. Will do once I get back.

**Pull request closed without merging**
